### PR TITLE
[framework] refactored checking duplicated e-mail to User constructor

### LINKED ISSUE #661: User::ChangeMail() does not check a domain
### What is happening

This description reflects changes done on https://github.com/shopsys/shopsys/pull/627.
`User::changeEmail()` does not take into account domain of given `$userByEmail` parameter. Therefore, it could throw `DuplicateEmailException` even when the passed user is from the other domain than the one whos email is edited.

### Expected result

`User::changeEmail()` should containt the same domain check the is in `UserFactory::create()`

### PR DESCRIPTION
**Pull request by simara-svatopluk**
| Q             | A
| ------------- | ---
|Description, reason for the PR| checking for duplicated e-mail was in two places - UserFactory and User entity, now it is only in entity. Fixed UniqueEmail validator in administration.
|New feature| No
|BC breaks| Yes
|Fixes issues| ... closes #661
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/tests/Unit/Model/Customer/UserFactoryTest.php [hunk 1]
```diff
@@ -172,20 +60,18 @@ private function getEncoderFactory(): EncoderFactory
     }
 
     /**
-     * @param \Shopsys\FrameworkBundle\Model\Customer\BillingAddressData|null $billingAddressData
      * @return \Shopsys\FrameworkBundle\Model\Customer\BillingAddress
      */
-    private function createBillingAddress(BillingAddressData $billingAddressData = null)
+    private function createBillingAddress()
```
Comment (vitek-rostislav) [inline packages/framework/tests/Unit/Model/Customer/UserFactoryTest.php]: it would be more readable if these changes were in a separate commit - they are not related to the rest of the changes, right?

File: packages/framework/src/Model/Customer/User.php [hunk 2]
```diff
@@ -166,15 +169,31 @@ public function changeEmail(string $email, ?self $userByEmail)
...
+     * @param int $domainId
+     * @param self|null $userByEmail
+     */
+    protected function checkDuplicateEmail(string $email, int $domainId, ?self $userByEmail): void
+    {
+        if ($userByEmail === null) {
+            return;
+        }
+
+        $isSameEmail = (mb_strtolower($userByEmail->getEmail()) === mb_strtolower($email));
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Customer/User.php]: getEmail() should already have a lowercased email
```suggestion
        $isSameEmail = ($userByEmail->getEmail() === mb_strtolower($email));
```

**Comment by grossmannmartin** [comment]
Hi @DavidOstrozlik, I tested this PR and everything seems all right. I did not find any troubling edge case.
