### PR TITLE
[framework] validation errors for the uploadedFilenames are displayed

### LINKED ISSUE #1558: Uploaded image with wrong extension causes 500
### What is happening
When you upload image with wrong extension like "test.exe" uploading will end by ImageNotFoundException. This is throwed in ImageProcessor::createInterventionImage().

### Expected result
There is some user friendly error displayed.

### PR DESCRIPTION
**Pull request by pesektomas**
| Q             | A
| ------------- | ---
|Description, reason for the PR| validation errors for the uploadedFilenames and currentFilenamesIndexedById are displayed
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues|  closes #1558 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/assets/js/common/validation/customizeBundle.js [hunk 1]
```diff
@@ -58,10 +58,17 @@ export default class CustomizeBundle {
             return;
         }
 
-        const isJsFileUpload = $domNode.closest('.js-file-upload').length > 0;
+        let isJsFileUpload = false;
+        if ($domNode.hasClass('js-validation-no-file-upload') === false) {
+            isJsFileUpload = $domNode.hasClass('js-validation-no-file-upload') === false || $domNode.closest('.js-file-upload').length > 0;
```
Comment (TomasLudvik) [inline packages/framework/assets/js/common/validation/customizeBundle.js:63]:
```suggestion
            isJsFileUpload = $domNode.closest('.js-file-upload').length > 0;
```

File: packages/framework/assets/js/admin/validation/form/validationMailTemplate.js [hunk 2]
```diff
@@ -9,7 +9,7 @@ export default function validationMailTemplate () {
         $(this).jsFormValidator({
             'groups': function () {
 
-                const groups = [constant('\\Shopsys\\FrameworkBundle\\Form\\ValidationGroup::VALIDATION_GROUP_DEFAULT')];
+                const groups = [constant('\\Symfony\\Component\\Validator\\Constraint::DEFAULT_GROUP')];
```
Comment (TomasLudvik) [inline packages/framework/assets/js/admin/validation/form/validationMailTemplate.js:12]: Is this necessary?

Comment (pesektomas) [reply packages/framework/assets/js/admin/validation/form/validationMailTemplate.js:12]: Yes, because `\\Shopsys\\FrameworkBundle\\Form\\ValidationGroup::VALIDATION_GROUP_DEFAULT` key does not exist.

Comment (pesektomas) [reply packages/framework/assets/js/admin/validation/form/validationMailTemplate.js]: 6f76fd4e04321393b2e2e83c2571da4c6f314642
