### PR TITLE
[framework] exchange rate recalculation after changing default currency

### LINKED ISSUE #2059: Wrong exchange rate after changing default currency
### What is happening
On v9.0, there is a problem with exchange rates after changing the default currency in admin.
After you change the default currency the exchange rate of old default currency is set to 1 instead of the correct value that should be calculated and exchange rates of other currencies are not correct as well.

eg.
CZK - default currency
EUR - exchange rate - 27,12 Kč per 1 €
GBP - exchange rate - 29,92 Kč per 1 £

after changing default currency to EUR

CZK - exchange rate - 1 € per 1 Kč
EUR - default currency
GBP - exchange rate - 29,91 € per 1 £

### Expected result
after changing default currency the exchange rate of old default currency should be calculated by the exchange rate.

from eg.
CZK - exchange rate - 0,037 € per 1 Kč
EUR - default currency
GBP - exchange rate - 1,10 € per 1 £

### PR DESCRIPTION
**Pull request by vitek-rostislav**
| Q             | A
| ------------- | ---
|Description, reason for the PR| see https://github.com/shopsys/shopsys/issues/2059
|New feature| Yes 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #2059  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/Model/Pricing/Currency/Currency.php [hunk 1]
```diff
@@ -19,6 +19,7 @@ class Currency
     public const ROUNDING_TYPE_INTEGER = 'integer';
 
     public const DEFAULT_EXCHANGE_RATE = '1';
+    public const CZK_EXCHANGE_RATE = '0.04';
```
Comment (s3tezsky) [inline packages/framework/src/Model/Pricing/Currency/Currency.php:22]: Do you think it would be wort to have more precise name of constant like `CZK_EXCHANGE_RATE_TO_EUR`?

File: packages/framework/src/Model/Pricing/Currency/CurrencyFacade.php [hunk 2]
```diff
@@ -227,6 +230,24 @@ public function setDomainDefaultCurrency(Currency $currency, $domainId)
...
 
+    /**
+     * @param \Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency $originalDefaultCurrency
+     * @param \Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency $newDefaultCurrency
+     */
+    protected function recalculateExchangeRatesByNewDefaultCurrency(
+        Currency $originalDefaultCurrency,
+        Currency $newDefaultCurrency
+    ): void {
+        $coefficient = Money::createFromFloat($originalDefaultCurrency->getExchangeRate() / $newDefaultCurrency->getExchangeRate(), 6);
```
Comment (s3tezsky) [inline packages/framework/src/Model/Pricing/Currency/CurrencyFacade.php:241]: As in previous commit: `$currency` should not be instance of money.

Besides it is the second occurence of the same calculation. Do you think it could be extracted into new method? Something like `getExchangeRateForCurrencies($inputCurrency, $outputCurrency)`

**Review by s3tezsky — COMMENTED** [review]
Good job down here! I have some minor points which would be nice to have.

File: upgrade/UPGRADE-v9.1.2-dev.md [hunk 3]
```diff
@@ -30,3 +30,7 @@ There you can find links to upgrade notes for other versions too.
 
 - update `ProductFilterPage` so it is resistant to case changes ([#2330](https://github.com/shopsys/shopsys/pull/2330))
     - see #project-base-diff to update your project
+
+- fix your data fixtures to set the proper exchange rate for the demo currencies (if you use the default demo setup) ([#2332](https://github.com/shopsys/shopsys/pull/2332))
+    - `PriceConverter::convertPriceWithoutVatToPriceInDomainDefaultCurrency` and `PriceConverter::convertPriceWithVatToPriceInDomainDefaultCurrency` now require new `$priceCurrency` argument
```
[the remark this answers is not in the document]
Comment (vitek-rostislav) [reply upgrade/UPGRADE-v9.1.2-dev.md:35]: agreed :+1:

File: packages/framework/src/Model/Pricing/Currency/Currency.php (hunk 1 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/Pricing/Currency/Currency.php]: yes, fixed in d426bbb2a

File: packages/framework/src/Model/Pricing/PriceConverter.php [hunk 4]
```diff
@@ -34,26 +35,47 @@ public function __construct(CurrencyFacade $currencyFacade, Rounding $rounding)
...
+     */
+    protected function convertPriceToPriceInDomainDefaultCurrency(Money $price, Currency $domainDefaultCurrency, ?Currency $priceCurrency = null): Money
+    {
+        if ($priceCurrency === null) {
+            trigger_error('$priceCurrency argument must be provided', E_USER_DEPRECATED);
+            $priceCurrencyExchangeRate = Currency::CZK_EXCHANGE_RATE;
+        } else {
+            $priceCurrencyExchangeRate = $priceCurrency->getExchangeRate();
+        }
+        $coefficient = Money::createFromFloat($priceCurrencyExchangeRate / $domainDefaultCurrency->getExchangeRate(), 6);
```
[the remark this answers is not in the document]
Comment (vitek-rostislav) [reply packages/framework/src/Model/Pricing/PriceConverter.php]: refactored in 277b3c648

File: packages/framework/src/Model/Pricing/Currency/CurrencyFacade.php (hunk 2 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/Pricing/Currency/CurrencyFacade.php]: refactored in 277b3c648

**Review by s3tezsky — APPROVED** [review]
Nice 👍

File: packages/framework/src/Model/Pricing/PriceConverter.php [hunk 5]
```diff
@@ -34,26 +35,47 @@ public function __construct(CurrencyFacade $currencyFacade, Rounding $rounding)
...
     }
 
     /**
      * @param \Shopsys\FrameworkBundle\Component\Money\Money $price
      * @param int $domainId
+     * @param \Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency|null $priceCurrency
      * @return \Shopsys\FrameworkBundle\Component\Money\Money
      */
-    public function convertPriceWithVatToPriceInDomainDefaultCurrency(Money $price, int $domainId): Money
+    public function convertPriceWithVatToPriceInDomainDefaultCurrency(Money $price, int $domainId, ?Currency $priceCurrency = null): Money
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Pricing/PriceConverter.php:55]: also a BC break

File: packages/framework/src/Model/Pricing/Currency/Currency.php [hunk 6]
```diff
@@ -19,6 +19,7 @@ class Currency
     public const ROUNDING_TYPE_INTEGER = 'integer';
 
     public const DEFAULT_EXCHANGE_RATE = '1';
+    public const CZK_EXCHANGE_RATE_TO_EUR = '0.04';
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Pricing/Currency/Currency.php:22]: Personally, I would rather see this constant in the DataFixture class. 
This may imply it's ok to put fixed exchange rates into application or use this one in the application.

File: packages/framework/src/Model/Pricing/PriceConverter.php [hunk 7]
```diff
@@ -34,26 +35,45 @@ public function __construct(CurrencyFacade $currencyFacade, Rounding $rounding)
...
+     * @param \Shopsys\FrameworkBundle\Component\Money\Money $price
+     * @param \Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency $domainDefaultCurrency
+     * @param \Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency|null $priceCurrency
+     * @return \Shopsys\FrameworkBundle\Component\Money\Money
+     */
+    protected function convertPriceToPriceInDomainDefaultCurrency(Money $price, Currency $domainDefaultCurrency, ?Currency $priceCurrency = null): Money
+    {
+        if ($priceCurrency === null) {
+            trigger_error('$priceCurrency argument must be provided', E_USER_DEPRECATED);
+            $priceCurrency = $this->currencyFacade->getByCode(Currency::CODE_CZK);
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Pricing/PriceConverter.php:73]: Can I ask why CZK? 
How it will behave when I don't set $priceCurrency? Is it possible some tests will fail?

**Review by grossmannmartin — CHANGES_REQUESTED** [review]

File: packages/framework/src/Model/Pricing/PriceConverter.php (hunk 7 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/Pricing/PriceConverter.php:73]: because right now, we are always sending prices in CZK currency to `PriceConverter`, see data fixtures and tests. So I wanted to keep this setting when no `$priceCurrency` is provided. I would not say that any test would fail if you do not set `$priceCurrency`

File: packages/framework/src/Model/Pricing/Currency/Currency.php (hunk 6 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/Pricing/Currency/Currency.php]: good point, fixed in a3e9ddb51

File: packages/framework/src/Model/Pricing/PriceConverter.php [hunk 8]
```diff
@@ -34,26 +35,47 @@ public function __construct(CurrencyFacade $currencyFacade, Rounding $rounding)
     /**
      * @param \Shopsys\FrameworkBundle\Component\Money\Money $price
      * @param int $domainId
+     * @param \Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency|null $priceCurrency
      * @return \Shopsys\FrameworkBundle\Component\Money\Money
      */
-    public function convertPriceWithoutVatToPriceInDomainDefaultCurrency(Money $price, int $domainId): Money
+    public function convertPriceWithoutVatToPriceInDomainDefaultCurrency(Money $price, int $domainId, ?Currency $priceCurrency = null): Money
```
[the remark this answers is not in the document]
Comment (vitek-rostislav) [reply packages/framework/src/Model/Pricing/PriceConverter.php:41]: that information made me a little bit less happy :joy:

[the remark this answers is not in the document]
Comment (vitek-rostislav) [reply packages/framework/src/Model/Pricing/PriceConverter.php]: I pushed my thought on how to solve this, see 698a2a4b7, I will be glad to discuss it with you and @s3tezsky tomorrow :slightly_smiling_face:

**Review by grossmannmartin — APPROVED** [review]

**Review by sslt — APPROVED** [review]
