### PR TITLE
[shopsys] fix calculation of transport and payment visibilities

### LINKED ISSUE #2302: FE API  return hidden transports and payments
## Describe the bug
If call FE query for transports with payments:
```
{
    query: transports {
        uuid
        payments {
            uuid
            name
        }
    }
}
```

return all payments where assigned to transport, regardless of whether they are visible for domain or hidden.

This problem is in payments query for transport:

```
{
    query: payments {
        uuid
        name
        transports {
            uuid
            name
        }
    }
}
```
return all transports where assigned to payment, regardless of whether they are visible for domain or hidden.

### Expected behavior
Payments and transport return only not hidden data, which can use in create order

### PR DESCRIPTION
**Pull request by TomasLudvik**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Attribute deleted of transport and payment was not used in consideration during calculation of their visibilities. Also transport and payment frontend API resolvers were not taking visibility in consideration.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #2302 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/frontend-api/src/Model/Resolver/Payment/PaymentResolver.php [hunk 1]
```diff
@@ -41,7 +41,7 @@ public function __construct(PaymentFacade $paymentFacade, Domain $domain)
     public function resolver(string $uuid): Payment
     {
         try {
-            return $this->paymentFacade->getByUuid($uuid);
+            return $this->paymentFacade->getVisibleByUuid($uuid);
```
Comment (grossmannmartin) [inline packages/frontend-api/src/Model/Resolver/Payment/PaymentResolver.php:44]: shouldn't be `PaymentCanBeUsedValidator` updated too?

File: packages/frontend-api/src/Model/Resolver/Transport/TransportResolver.php [hunk 2]
```diff
@@ -41,7 +41,7 @@ public function __construct(TransportFacade $transportFacade, Domain $domain)
     public function resolver(string $uuid): Transport
     {
         try {
-            return $this->transportFacade->getByUuid($uuid);
+            return $this->transportFacade->getVisibleByUuid($uuid);
```
Comment (grossmannmartin) [inline packages/frontend-api/src/Model/Resolver/Transport/TransportResolver.php:44]: Shouldn't be `TransportCanBeUsedValidator` updated too?

**Review by grossmannmartin — CHANGES_REQUESTED** [review]
Is the base set as "master" correct? I see the milestone set to 9.1.2

File: packages/frontend-api/src/Model/Resolver/Payment/PaymentResolver.php (hunk 1 above)
Comment (TomasLudvik) [reply packages/frontend-api/src/Model/Resolver/Payment/PaymentResolver.php:44]: Yes, nice catch!

File: packages/frontend-api/src/Model/Resolver/Transport/TransportResolver.php (hunk 2 above)
Comment (TomasLudvik) [reply packages/frontend-api/src/Model/Resolver/Transport/TransportResolver.php:44]: Yes, nice catch!

**Comment by grossmannmartin** [comment]
While testing I found two scenarios that may be problematic:

- when I disable transport/payment on the domain, I still can obtain such transport/payment with graphql query
- when I try to use deleted transport/payment to create an order, I get a different validation error than on non-existing

deleted transport:
```
"validation": {
    "input": [
        {
            "message": "Please choose a valid combination of transport and payment",
            "code": "46ccd6d3-61e7-4a34-a42a-b13b92291e28"
        }
    ],
    "input.transport": [
        {
            "message": "Transport bfa48e3a-007d-4e19-97ab-5692f8cff1c5 doesn't exist",
            "code": "1f2d316b-3edd-4869-bba6-b234856a7783"
        }
    ]
}
```

non-existing:

```
"validation": {
    "input.transport": [
        {
            "message": "Transport bfa48e3a-007c-4e19-97ab-5692f8cff1c5 doesn't exist",
            "code": "1f2d316b-3edd-4869-bba6-b234856a7783"
        }
    ]
},
```

File: packages/framework/src/Model/Payment/PaymentRepository.php [hunk 3]
```diff
@@ -113,4 +114,30 @@ public function getOneByUuid(string $uuid): Payment
...
+     */
+    public function getEnabledOnDomainByUuid(string $uuid, int $domainId): Payment
+    {
+        $queryBuilder = $this->getPaymentRepository()->createQueryBuilder('p')
+            ->join(PaymentDomain::class, 'pd', Join::WITH, 'p.id = pd.payment AND pd.domainId = :domainId')
+            ->setParameter('domainId', $domainId)
+            ->where('p.uuid = :uuid')
+            ->setParameter('uuid', $uuid)
+            ->andWhere('p.deleted = false')
+            ->setParameter('uuid', $uuid)
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Payment/PaymentRepository.php:131]: duplicated line :)

**Review by grossmannmartin — APPROVED** [review]

**Review by sslt — APPROVED** [review]
