### PR TITLE
[framework] RegisterProjectFrameworkClassExtensionCompilerPass now ensures that both class and interface alias are registered in Symfony services

### LINKED ISSUE #2400: Annotations fixer not working when extending class by its interface
## Describe the bug

Annotation fixer does not fix my extended class declared like this in services.yaml
```
Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserDataFactoryInterface:
    alias: App\Model\Customer\User\CustomerUserDataFactory
```
but will fix when extended like this:
```
Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserDataFactory:
    alias: App\Model\Customer\User\CustomerUserDataFactory
```
### Expected behavior

Annotation fixer works in both cases

### LINKED ISSUE #2539: annotation fixer ignores services extended with `class` keyword
## Describe the bug
When service is extended with the `class` keyword (for example when tagging is needed) 

```yaml
    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityFacade:
        class: App\Model\Product\ProductVisibilityFacade
        tags:
            # must be ran after CategoryVisibilityRepository and ProductPriceRecalculator
            - {
                name: kernel.event_listener,
                event: kernel.response,
                method: onKernelResponse,
                priority: 10,
                }
```

Annotation fixer do not change annotations at all.  

When `alias` is used

```yaml
    Shopsys\FrameworkBundle\Model\Product\ProductVisibilityFacade:
        alias: App\Model\Product\ProductVisibilityFacade
```

Everything work as expected.

### Expected behavior
Annotations for services extended with `class` keyword are replaced the same way as they are with `alias`, or the behavior is documented, if it's intentional.

### PR DESCRIPTION
**Pull request by TomasLudvik**
| Q             | A
| ------------- | ---
|Description, reason for the PR| All variants of service needs to be registered in class extension for annotation fixer to work correctly.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #2400 closes #2539  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php [hunk 1]
```diff
@@ -16,11 +20,26 @@ class RegisterProjectFrameworkClassExtensionsCompilerPass implements CompilerPas
...
             if ($this->isFrameworkClassWithAlias($container, $serviceId)) {
                 $aliasId = (string)$container->getAlias($serviceId);
+
+                try {
+                    $serviceClass = $container->findDefinition($serviceId)->getClass();
+                } catch (ServiceNotFoundException) {
+                    $serviceClass = null;
+                }
+
+                if ($serviceClass !== null && !$this->isProjectClass($aliasId) && $this->isProjectClass($serviceClass)) {
```
Comment (grossmannmartin) [inline packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php:34]: This check is done only if the service is already aliased... meaning this condition can be met only if
- current service is a framework class
- current service has the alias defined
- the alias is not a project class
- current service has the class set as a project class

how should look the definition to meet these conditions?

File: packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php [hunk 2]
```diff
@@ -44,4 +63,29 @@ private function isProjectClass(string $serviceId): bool
...
+     * @param \Symfony\Component\DependencyInjection\Definition $classExtensionRegistryDefinition
+     * @param string $aliasId
+     */
+    private function addAllVariantsOfServiceToClassExtension(
+        ReflectionClass $frameworkClassBetterReflection,
+        Definition $classExtensionRegistryDefinition,
+        string $aliasId
+    ): void {
+        if ($frameworkClassBetterReflection->isInterface()) {
+            $className = rtrim($frameworkClassBetterReflection->getName(), 'Interface');
```
Comment (grossmannmartin) [inline packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php:78]: rtrim does not work as presumed here. 

for example  
`rtrim('Myface', 'Interface')` results in `My` 
`rtrim('MyFacadeInterface', 'Interface')` result in `MyFacad`

Maybe `preg_replace('/Interface$/', '', $string);` would be a better choice

File: packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php [hunk 3]
```diff
@@ -44,4 +63,29 @@ private function isProjectClass(string $serviceId): bool
...
+
+            if (class_exists($className)) {
+                $classExtensionRegistryDefinition->addMethodCall('addExtendedService', [$className, $aliasId]);
+            }
+        } else {
+            $interfaceName = $frameworkClassBetterReflection->getName() . 'Interface';
+
+            if (interface_exists($interfaceName)) {
```
Comment (grossmannmartin) [inline packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php:86]: Wouldn't be nice also to check whether the class implements the interface?

If I just create the `Shopsys\FrameworkBundle\Model\Cart\Watcher\CartWatcherFacadeInterface` interface, the link between this interface and ordinary CartWatcherFacade will be created in the service extension map, even though it does not make sense at this point

**Review by grossmannmartin — CHANGES_REQUESTED** [review]

File: packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php (hunk 1 above)
Comment (TomasLudvik) [reply packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php:34]: This happens when class is extended in services.yaml instead of aliasing.

Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserUpdateDataFactory:
    class: App\Model\Customer\User\CustomerUserUpdateDataFactory

File: packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php (hunk 2 above)
Comment (TomasLudvik) [reply packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php:78]: Changed

File: packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php (hunk 3 above)
Comment (TomasLudvik) [reply packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php:86]: Added

File: packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php (hunk 1 above)
Comment (grossmannmartin) [reply packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php:34]: This class will work, because it implements the interface and this interface has defined alias in services.yaml (https://github.com/shopsys/shopsys/blob/master/packages/framework/src/Resources/config/services.yaml#L756) 

I tried it this way: 
- create new `\App\Model\Product\TopProduct\TopProductFacade` class extending the framework's one
- create new `\App\Controller\Admin\TopProductController`class extending the framework's one
- extend it in services.yaml with the `class`
    ```
    Shopsys\FrameworkBundle\Model\Product\TopProduct\TopProductFacade:
        class: App\Model\Product\TopProduct\TopProductFacade
    ```
- run `php phing annotations-fix`

In the current implementation, only `@method \App\Model\Product\Product[] getProductsForDomain(int $domainId)` annotation is added. 

Expected is also the annotation for the constructor and property `$topProductFacade`

Comment (grossmannmartin) [reply packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php]: I have tested it on our internal project and I got the `You have requested a non-existent service "App\Model\Mail\MailTemplateConfiguration".` error.

Can you check it, please?

**Review by grossmannmartin — APPROVED** [review]
