### PR TITLE
[shopsys] use DBAL native queries for DML instead of ORM Native SQL

### LINKED ISSUE #2121: Wrong usage of Doctrine native queries
## Describe the bug

Native queries should be used only for SELECT queries. In SSFW codebase there are a lot of native queries with insert/update/delete behavior. This can be a problem for large projects that need database replication because native queries are queried to replica databases. That will throw an exception.

Doctrine native query documentation: https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/native-sql.html
Additional info about replication doctrine: https://github.com/doctrine/dbal/blob/2.12.x/lib/Doctrine/DBAL/Connections/PrimaryReadReplicaConnection.php#L19

### Expected behavior

Native queries should be checked and adjusted to avoid run destructive SQL operations with `createNativeQuery`

PS: If you need more information, please contact me :)

### PR DESCRIPTION
**Pull request by grossmannmartin**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Native queries for DELETE, UPDATE or INSERT statements now don't use [ORM Native SQL API](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/native-sql.html). `EntityManager::getConnection()` to access the native database connection and the `executeStatement()` method for these queries is used instead to ensure working application with database replication configured (see [PrimaryReadReplicaConnection class](https://github.com/doctrine/dbal/blob/2.12.x/lib/Doctrine/DBAL/Connections/PrimaryReadReplicaConnection.php#L19))
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #2121  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

DB Replication cannot be yet used as `\Shopsys\FrameworkBundle\Component\HttpFoundation\TransactionalMasterRequestListener` always create a transaction (start transaction automatically reconnects to the master) – related PR #2122 

Minimum configuration for testing can be in `doctrine.yaml` file (don't forget to update `test/doctrine.yaml`, or the tests will fail)
```
# Master listens on the port 5454, replica on port 5455
doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: 5454
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8
        # Explicitly define server version to overcome the need to connect to the database in early
        # initialization phase (during DIC service creation) for auto-detecting version from the server.
        # See \Doctrine\DBAL\Connection::getDatabasePlatformVersion().
        server_version: "%database_server_version%"
        slaves:
            # A collection of named replica connections (e.g. replica1, replica2)
            reader:
                dbname: "%database_name%"
                host: "%database_host%"
                port: 5455
                user: "%database_user%"
                password: "%database_password%"
                charset: UTF8
```

for running postgre with replicas can be used https://github.com/2hamed/docker-pg-replication 
(older version of postgresql is used, don't try to update to 12 as used recovery.conf is no longer available)

### CODE REVIEW

File: packages/framework/src/Component/Setting/SettingValueRepository.php [hunk 1]
```diff
@@ -54,12 +54,16 @@ public function copyAllMultidomainSettings($fromDomainId, $toDomainId)
                     WHERE domain_id IS NOT NULL
                         AND domain_id != :commonDomainId
                 )',
-            new ResultSetMapping()
+            [
+                'toDomainId' => $toDomainId,
```
Comment (s3tezsky) [inline packages/framework/src/Component/Setting/SettingValueRepository.php:58]: I am not really happy about duplicating these keys. But I am woried there is no other way than introduce costants for all of them which may worse readibility... What do you think?

File: packages/framework/src/Model/Product/Pricing/ProductCalculatedPriceRepository.php [hunk 2]
```diff
@@ -70,14 +70,16 @@ public function saveCalculatedPrice(Product $product, PricingGroup $pricingGroup
...
     public function createProductCalculatedPricesForPricingGroup(PricingGroup $pricingGroup)
     {
-        $query = $this->em->createNativeQuery(
+        $this->em->getConnection()->executeStatement(
             'INSERT INTO product_calculated_prices (product_id, pricing_group_id, price_with_vat)
             SELECT id, :pricingGroupId, :priceWithVat FROM products',
-            new ResultSetMapping()
+            [
+                'pricingGroupId' => $pricingGroup->getId(),
+                'priceWithVat' => null,
```
Comment (s3tezsky) [inline packages/framework/src/Model/Product/Pricing/ProductCalculatedPriceRepository.php:78]: Could not be the `NULL` set in query directly?

File: packages/framework/src/Model/Product/ProductVisibilityRepository.php [hunk 3]
```diff
@@ -111,16 +109,20 @@ protected function refreshGlobalProductVisibility($onlyMarkedProducts)
...
     {
-        $query = $this->em->createNativeQuery(
+        $this->em->getConnection()->executeStatement(
             'INSERT INTO product_visibilities (product_id, pricing_group_id, domain_id, visible)
             SELECT id, :pricingGroupId, :domainId, :calculatedVisibility FROM products',
-            new ResultSetMapping()
+            [
+                'pricingGroupId' => $pricingGroup->getId(),
+                'domainId' => $domainId,
+                'calculatedVisibility' => false,
```
Comment (s3tezsky) [inline packages/framework/src/Model/Product/ProductVisibilityRepository.php:118]: Is it necessary to pass static value by parameter?

File: packages/framework/src/Model/Product/ProductVisibilityRepository.php [hunk 4]
```diff
@@ -278,12 +286,13 @@ protected function hideVariantsWithInvisibleMainVariant($onlyMarkedProducts)
                         AND mpv.visible = FALSE
                 )
             ' . $onlyMarkedProductsCondition,
-            new ResultSetMapping()
+            [
+                'variantTypeVariant' => Product::VARIANT_TYPE_VARIANT,
```
Comment (s3tezsky) [inline packages/framework/src/Model/Product/ProductVisibilityRepository.php:290]: Maybe this static value should not be passed by parameter as well.

File: project-base/src/DataFixtures/Demo/ImageDataFixture.php [hunk 5]
```diff
@@ -254,21 +254,28 @@ private function processSliderItemsImages()
...
             VALUES (:id, :entity_name, :entity_id, :type, :extension, :position, :modified_at)',
-            new ResultSetMapping()
+            [
+                'id' => $imageId,
+                'entity_name' => $entityName,
+                'entity_id' => $entityId,
+                'type' => null,
+                'extension' => self::IMAGE_TYPE,
+                'position' => null,
+                'modified_at' => new DateTimeImmutable('2015-04-16 11:36:06'),
```
Comment (s3tezsky) [inline project-base/src/DataFixtures/Demo/ImageDataFixture.php:267]: Not necessary to use parameters.

File: upgrade/UPGRADE-v9.1.0-dev.md [hunk 6]
```diff
@@ -249,3 +249,6 @@ There you can find links to upgrade notes for other versions too.
 
 - added total count to frontend API connections ([#2141](https://github.com/shopsys/shopsys/pull/2141))
     - see #project-base-diff to update your project
+
+- use DBAL native queries for DML instead of ORM Native SQL ([#2148](https://github.com/shopsys/shopsys/pull/2148))
+    - see #project-base-diff to update your project
```
Comment (s3tezsky) [inline upgrade/UPGRADE-v9.1.0-dev.md:254]: I am missing a hint about type defining. I belive it could be handy.

**Review by s3tezsky — CHANGES_REQUESTED** [review]

File: packages/framework/src/Component/Domain/Multidomain/MultidomainEntityDataCreator.php [hunk 7]
```diff
@@ -71,16 +71,19 @@ protected function copyMultidomainDataForNewDomain($templateDomainId, $newDomain
...
             SELECT :newDomainId, ' . $quotedColumnNamesSql . '
             FROM ' . $quotedTableName . '
             WHERE domain_id = :templateDomainId',
-            new ResultSetMapping()
+            [
+                'newDomainId' => $newDomainId,
+                'templateDomainId' => $templateDomainId,
+            ],
+            [
+                'newDomainId' => Types::INTEGER,
```
[the remark this answers is not in the document]
Comment (grossmannmartin) [reply packages/framework/src/Component/Domain/Multidomain/MultidomainEntityDataCreator.php:84]: the default value is `string`, I'm not sure whether it's necessary, but I think more strict types cannot harm.

File: docs/model/introduction-to-model-architecture.md [hunk 8]
```diff
@@ -117,16 +117,16 @@ class CartRepository
     }
 
     /**
-     * @param \Shopsys\FrameworkBundle\Model\Customer\CustomerIdentifier $customerIdentifier
+     * @param \Shopsys\FrameworkBundle\Model\Customer\User\CustomerUserIdentifier $customerUserIdentifier
      * @return \Shopsys\FrameworkBundle\Model\Cart\Cart|null
      */
-    public function findByCustomerIdentifier(CustomerIdentifier $customerIdentifier)
```
[the remark this answers is not in the document]
Comment (grossmannmartin) [reply docs/model/introduction-to-model-architecture.md:123]: Great idea, I created #2149 and rebased this PR on that

File: packages/framework/src/Component/Setting/SettingValueRepository.php (hunk 1 above)
Comment (grossmannmartin) [reply packages/framework/src/Component/Setting/SettingValueRepository.php:58]: I see... introducing a constant is a cleaner solution, but I'm worried about worse readability as you mentioned. 
Now I see the appropriate key in SQL string and in parameter arrays. 

Or I can rewrite those queries to use positional parameters (numerically indexed arrays – no keys), but for me it's more clear as it is right now.

File: packages/framework/src/Model/Product/Pricing/ProductCalculatedPriceRepository.php (hunk 2 above)
Comment (grossmannmartin) [reply packages/framework/src/Model/Product/Pricing/ProductCalculatedPriceRepository.php]: Good point. fixed in 706c46209

File: packages/framework/src/Model/Product/ProductVisibilityRepository.php (hunk 3 above)
Comment (grossmannmartin) [reply packages/framework/src/Model/Product/ProductVisibilityRepository.php]: Good point. fixed in 706c46209

File: packages/framework/src/Model/Product/ProductVisibilityRepository.php (hunk 4 above)
Comment (grossmannmartin) [reply packages/framework/src/Model/Product/ProductVisibilityRepository.php:288]: I prefer to keep as the parameter as it's bound to product and usage of the value can be easily found.

File: project-base/src/DataFixtures/Demo/ImageDataFixture.php (hunk 5 above)
Comment (grossmannmartin) [reply project-base/src/DataFixtures/Demo/ImageDataFixture.php]: removed unnecessary in 2bf489594. 
extension kept on purpose as it's more readable than escaped apostrophes in sql string.

File: upgrade/UPGRADE-v9.1.0-dev.md (hunk 6 above)
Comment (grossmannmartin) [reply upgrade/UPGRADE-v9.1.0-dev.md]: Good point. added in b67e1b1be

**Review by s3tezsky — APPROVED** [review]

**Review by sslt — APPROVED** [review]
