### PR TITLE
[framework] fixed loading of multi design templates

### LINKED ISSUE #2042: Creating a Multidomain Design is not possible
### What is happening
Templates can no longer be overriden for specific domain as described in cookbook https://docs.shopsys.com/en/9.0/cookbook/creating-a-multidomain-design/#scenario-2-i-want-to-change-layout-in-footer-on-my-2nd-domain

Class responsible for loading multidomain templates (`Shopsys\FrameworkBundle\Component\Domain\Multidomain\Twig\FilesystemLoader`) seems unused and service definition does not feel right as constructor of the class accepts only two arguments 

```yaml
twig.loader.filesystem:
        class: Shopsys\FrameworkBundle\Component\Domain\Multidomain\Twig\FilesystemLoader
        arguments:
            $locator: '@templating.locator'
            $parser: '@templating.name_parser'
            $rootPath: '%kernel.project_dir%'
            $domain: '@Shopsys\FrameworkBundle\Component\Domain\Domain'
```

It seems that in container is the loader registered with different id (`twig.loader.native_filesystem`)

### Expected result

I can follow cookbook to create a multidomain templates.
Test for this multidomain template feature exists.

### PR DESCRIPTION
**Pull request by TomasLudvik**
| Q             | A
| ------------- | ---
|Description, reason for the PR| With upgrade on Symfony 4 there has been changes in FilesystemLoaders and it caused our FilesystemLoader to not be used anymore. This PR fixes that and adds test to check, if it is working correctly in the future.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #2042  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Review by s3tezsky — APPROVED** [review]
EPIC!

File: project-base/tests/App/Functional/Twig/FilesystemLoaderTest.php [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+        $domainReflection = $twigReflection->getProperty('domain');
+        $domainReflection->setAccessible(true);
+        $domainReflection->setValue($twigFilesystemLoader, $domain);
+
+        $fileOutput = $twig->render('Front/Tests/twigLoader.html.twig');
+
+        $domainReflection->setValue($twigFilesystemLoader, $this->domain);
+        $domainReflection->setAccessible(false);
+
+        $this->assertSame('Hello world', trim($fileOutput));
```
Comment (grossmannmartin) [inline project-base/tests/App/Functional/Twig/FilesystemLoaderTest.php:38]: Thanks for the test! 

What do you think of the following?

```php
$setting = $this->createMock(Setting::class);
        $twig = $this->getContainer()->get('twig');

        $twigFilesystemLoader = $this->getContainer()->get('twig.loader.native_filesystem');
        $twigFilesystemLoader->addPath(__DIR__ . '/Resources');

        $domainConfigWithoutCustom = new DomainConfig(
            1,
            'http://webserver:8080',
        'domain1',
            'en',
            'sa',
            ''
        );

        $domainConfigWithCustom = new DomainConfig(
            2,
            'http://webserver:8080',
            'domain2',
            'en',
            'sa',
            'custom'
        );

        $domain = new Domain([$domainConfigWithoutCustom, $domainConfigWithCustom], $setting);

        $twigReflection = new \ReflectionClass($twigFilesystemLoader);
        $domainReflection = $twigReflection->getProperty('domain');
        $domainReflection->setAccessible(true);
        $domainReflection->setValue($twigFilesystemLoader, $domain);

        $domain->switchDomainById(1);
        $fileOutput = $twig->render('Front/twigLoader.html.twig');
        self::assertSame('Hello world', trim($fileOutput));

        $domain->switchDomainById(2);
        $fileOutput = $twig->render('Front/twigLoader.html.twig');
        self::assertSame('Hello world custom', trim($fileOutput));
```

It has several advantages. 
 - I don't need settings service registered as public (used mock)
 - I test custom designId and normal (no designId)
 - Template used for tests only are in test folder (project-base/tests/App/Functional/Twig/Resources/Front/twigLoader.custom.html.twig and project-base/tests/App/Functional/Twig/Resources/Front/twigLoader.html.twig have to be created)
 - less reflection for domainconfig as it's created manually

**Review by grossmannmartin — CHANGES_REQUESTED** [review]
Can you check please? I have suggestion for test

File: packages/framework/src/Component/Domain/Multidomain/Twig/FilesystemLoader.php [hunk 2]
```diff
@@ -13,14 +13,16 @@ class FilesystemLoader extends BaseFilesystemLoader
     protected $domain;
 
     /**
+     * @param array $paths
      * @param string|null $rootPath
      * @param \Shopsys\FrameworkBundle\Component\Domain\Domain|null $domain
      */
     public function __construct(
+        array $paths = [],
```
[the remark this answers is not in the document]
Comment (TomasLudvik) [reply packages/framework/src/Component/Domain/Multidomain/Twig/FilesystemLoader.php:21]: People are not even able to easily extend that class so I hope it is ok.

File: project-base/tests/App/Functional/Twig/FilesystemLoaderTest.php (hunk 1 above)
Comment (TomasLudvik) [reply project-base/tests/App/Functional/Twig/FilesystemLoaderTest.php]: Ok I have updated it

File: project-base/config/services_test.yaml [hunk 3]
```diff
@@ -75,3 +75,5 @@ services:
     Shopsys\FrameworkBundle\Model\Pricing\Rounding: ~
 
     Shopsys\FrontendApiBundle\Model\Token\TokenFacade: ~
+
+    Shopsys\FrameworkBundle\Component\Setting\Setting: ~
```
Comment (grossmannmartin) [inline project-base/config/services_test.yaml:79]: This is no longer necessary as Setting class is mocked in test

File: packages/framework/src/Component/Domain/Multidomain/Twig/FilesystemLoader.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (grossmannmartin) [reply packages/framework/src/Component/Domain/Multidomain/Twig/FilesystemLoader.php:21]: ok

**Review by grossmannmartin — APPROVED** [review]

File: project-base/config/services_test.yaml (hunk 3 above)
Comment (TomasLudvik) [reply project-base/config/services_test.yaml:79]: fixed

**Review by sslt — APPROVED** [review]
