### PR TITLE
ProductSearchCreateStructureCommand exits on error

### LINKED ISSUE #936: Successfully phing target product-search-create-structure with error
### What is happening
Phing target `product-search-create-structure` is successfully finished without exists JSON configuration for new domain.

Add new domain, run `build-demo-dev`, fix datafixtures...
Build fails on this error:
```
Shopsys Framework > product-search-export-products:

Exporting products to microservice
05:32:49 ERROR     [app] Elasticsearch\Common\Exceptions\Missing404Exception: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"product3","index_uuid":"_na_","index":"product3"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"product3","index_uuid":"_na_","index":"product3"},"status":404} (uncaught exception) at /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php line 607 while running console command `shopsys:product-search:export-products` ["exception" => Elasticsearch\Common\Exceptions\Missing404Exception { …}]
```
It is very weird for me... Now I know, that I forgot to create `3.json` but firstly I was looking for a mistake elsewhere. Later I noticed error during phing target `product-search-create-structure` like this:
```
[ERROR] File /var/www/html/app/../src/Shopsys/ShopBundle/Resources/definition//product/3.json not found
```
From this error I dont have idea what was happend... What is it `3.json` in this general filepath? Ok, maybe error is double slash in this filepath... Oh, wait! 3.json is probably something for new domain.

### Expected result
I expect failing `product-search-create-structure` target without all needed configs.
I want better descriptive error on missing this config files
I hope for better filepath or filename for this configs (I am going to create next issue for move this configurations from JSON to PHP)

### PR DESCRIPTION
**Pull request by MattCzerner**
| Q             | A
| ------------- | ---
|Description, reason for the PR| ProductSearchCreateStructureCommand was outputting successful exit codes even if it failed. This PR makes sure that developer will not overlook errors that this command can output.
|New feature| No
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No 
|Fixes issues| fixes #936 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/Component/Elasticsearch/ElasticsearchStructureManager.php [hunk 1]
```diff
@@ -85,7 +85,14 @@ protected function getDefinition(int $domainId, string $index): array
     {
         $file = sprintf('%s/%s/%s.json', $this->definitionDirectory, $index, $domainId);
         if (!is_file($file)) {
-            throw new ElasticsearchStructureException(sprintf('File %s not found', $file));
+            throw new ElasticsearchStructureException(
+                sprintf(
+                    'Definition file %d.json, for domain: %d, not found in definition folder "%s". Please make sure that for each domain exists a definition json file with name of a domain ID',
```
[the remark this answers is not in the document]
Comment (PetrHeinz) [reply packages/framework/src/Component/Elasticsearch/ElasticsearchStructureManager.php]: Personally, I would use the [argument swapping](https://www.php.net/manual/en/function.sprintf.php#refsect1-function.sprintf-examples) for all variables or for none. And I'd prefer to use it because of DRY.

```suggestion
                    'Definition file %1$d.json, for domain: %1$d, not found in definition folder "%2$s". Please make sure that for each domain exists a definition json file with name of a domain ID',
```

File: packages/framework/src/Component/Elasticsearch/ElasticsearchStructureManager.php [hunk 2]
```diff
@@ -87,7 +87,7 @@ protected function getDefinition(int $domainId, string $index): array
         if (!is_file($file)) {
             throw new ElasticsearchStructureException(
                 sprintf(
-                    'Definition file %d.json, for domain: %1$d, not found in definition folder "%s". Please make sure that for each domain exists a definition json file with name of a domain ID',
+                    'Definition file %d.json, for domain ID %1$d, not found in definition folder "%s". Please make sure that for each domain exists a definition json file named by the corresponding domain ID',
```
Comment (boris-brtan) [inline packages/framework/src/Component/Elasticsearch/ElasticsearchStructureManager.php]: ?? `for domain with ID ` ??
Maybe you can use PHP_EOL as separator after the first sentence 
But OK.

Comment (vitek-rostislav) [reply packages/framework/src/Component/Elasticsearch/ElasticsearchStructureManager.php]: PHP_EOL added, the first suggestion not :grin:
