### PR TITLE
fix friendly url data providers

### LINKED ISSUE #945: ProductListFriendlyUrlDataProvider variables mismatch
ProductListFriendlyUrlDataProvider

In class **framework/src/Model/Product/ProductListFriendlyUrlDataProvider.php**  line 62 and 63 there is variable mismatch. Variables 'id' and 'name' are switched:

            $friendlyUrlData->name = $data['id'];
            $friendlyUrlData->id = $data['name'];

instead of:

            $friendlyUrlData->id = $data['id'];
            $friendlyUrlData->name = $data['name'];

### LINKED ISSUE #1174: broken Friendly URL generation
<!--- Title should contain short general summary what is the issue about -->

### What is happening
When I try to generate friendly URLs for my entity using `php phing friendly-urls-generate`, I got an error:
```
09:46:53 ERROR     [app] Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFactory::createIfValid() must be of the type int, string given, called in /var/www/html/packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php on line 90 (uncaught exception) at /var/www/html/packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFactory.php line 47 while running console command `shopsys:generate:friendly-url` ["exception" => Symfony\Component\Debug\Exception\FatalThrowableError { …}]
09:46:53 ERROR     [console] Error thrown while running command "shopsys:generate:friendly-url". Message: "Argument 2 passed to Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFactory::createIfValid() must be of the type int, string given, called in /var/www/html/packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php on line 90" ["exception" => TypeError { …},"command" => "shopsys:generate:friendly-url","message" => "Argument 2 passed to Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFactory::createIfValid() must be of the type int, string given, called in /var/www/html/packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php on line 90"]
09:46:53 ERROR     [app] Command `shopsys:generate:friendly-url` exited with status code 1

In FriendlyUrlFactory.php line 47:
                                                                                                                                                                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                                                  
  Type error: Argument 2 passed to Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFactory::createIfValid() must be of the type int, string given, called in /var/www/html/packages/frame  
  work/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php on line 90                                                                                                                                   
                                                                                                                                                                                                           

Exception trace:
 () at /var/www/html/packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFactory.php:47
 Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFactory->createIfValid() at /var/www/html/packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php:90
 Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlFacade->createFriendlyUrlForDomain() at /var/www/html/packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGeneratorFacade.php:110
 Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlGeneratorFacade->generateUrlsByRoute() at /var/www/html/packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGeneratorFacade.php:80
 Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlGeneratorFacade->generateUrlsByDomainConfig() at /var/www/html/packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGeneratorFacade.php:59
 Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlGeneratorFacade->generateUrlsForSupportedEntities() at /var/www/html/packages/framework/src/Command/GenerateFriendlyUrlCommand.php:46
 Shopsys\FrameworkBundle\Command\GenerateFriendlyUrlCommand->execute() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:987
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/html/project-base/app/Bootstrap.php:63
 Shopsys\Bootstrap->run() at /var/www/html/project-base/bin/console:17
```

To reproduce the behavior, one must either create a new friendly URL generator for some entity, or `friendly_urls` table must be deleted before the phing target is run, otherwise the target does nothing as all the friendly URLs are already created (during the entities creation in data fixtures)
<!--- What are preconditions and your setting e.g. Shopsys version or in case of Docker issues your operating system -->

<!--- Best is to include steps to reproduce this issue if relevant-->

<!--- Tell us what happens -->

### Expected result
It is possible to generate friednly URLS using `php phing friendly-urls-generate` command
<!--- Tell us what should happen instead -->

### PR DESCRIPTION
**Pull request by vitek-rostislav**
| Q             | A
| ------------- | ---
|Description, reason for the PR| mismatch in variables assignments reported in #945 
|New feature| No 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No 
|Fixes issues| closes #945, closes #1174 
|Standards and tests pass| Yes
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

**Comment by grossmannmartin** [comment]
Hi, nice. 
I'm curious, why this PR shows 60 commits it's actually just one, could rebase help?
Also, in the issue #945 is a comment from Jan, could you please answer him? I believe there is no problem.

But approve :+1:

**Comment by vitek-rostislav** [comment]
Hi, thanks for the review :+1: 

> I'm curious, why this PR shows 60 commits it's actually just one, could rebase help?

Yes, it was my mistake (the PR was targeted against master originally). I rebased the branch on `8.0` :wink: 

> Just wondering about upgrade notes. Should there be any?

:thinking: Hm, I have removed one method from `FriendlyUrlDataFactory` - there should be an upgrade note. I have added it in a fixup commit. For the other changes, I do not think any upgrade notes are needed

**Comment by grossmannmartin** [comment]
### Tests
I did some testing and generating of URL for brands and articles is okay, but I found another error in
`ProductListFriendlyUrlDataProvider` and `ProductDetailFriendlyUrlDataProvider` classes.

in both of classes near line 50 is following ` ->setParameter('locale', $domainConfig->getId())`, resulting in empty data from query because there is no locale named 1 (for instance :))
It should be like ` ->setParameter('locale', $domainConfig->getLocale())`

Currently, product detail and product list friendly URLs are not generated.

**Comment by PetrHeinz** [comment]
@vitek-rostislav I'm wondering why you haven't fixed the actual implementation of the `FriendlyUrlDataFactory::createFromData()` method and use it instead of fixing the implementation in the four places (which can be seen as a [DRY violation](https://github.com/shopsys/shopsys/blob/v7.2.0/docs/contributing/code-quality-principles.md#dont-repeat-yourself))...

As a side-effect, this would also remove the need for the BC break.

**Comment by vitek-rostislav** [comment]
Hi @PetrHeinz, thanks for pointing this out, for some reason, this has not occurred to me :man_facepalming: I will fix it this way :+1:

File: packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php [hunk 1]
```diff
@@ -54,9 +54,20 @@ public function getFriendlyUrlData(DomainConfig $domainConfig): array
         $friendlyUrlsData = [];
 
         foreach ($scalarData as $data) {
-            $friendlyUrlData = $this->friendlyUrlDataFactory->create();
-            $friendlyUrlData->name = $data['id'];
-            $friendlyUrlData->id = $data['name'];
+            if (method_exists($this->friendlyUrlDataFactory, 'createFromIdAndName')) {
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php]: `method_exists` in a loop seems inefficient to me

File: packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php [hunk 2]
```diff
@@ -54,9 +54,20 @@ public function getFriendlyUrlData(DomainConfig $domainConfig): array
...
+                    sprintf(
+                        'This approach is deprecated since Shopsys Framework 7.3, implement and use "%s" instead',
+                        FriendlyUrlDataFactoryInterface::class . '::createFromIdAndName()'
+                    ),
+                    E_USER_DEPRECATED
+                );
+                $friendlyUrlData = $this->friendlyUrlDataFactory->create();
+                $friendlyUrlData->id = $data['id'];
+                $friendlyUrlData->name = $data['name'];
+            }
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php]: The whole method is quite hard to read. Can you please extract some parts into methods?
I thought about 
```php 
if (method_exists($this->friendlyUrlDataFactory, 'createFromIdAndName')) {
    return $this->getDataTheNewWay();
} else {
    return $this->getDataTheOldFashionWay();
}
```
I know there will be for loop in both methods, but It helps extensibility and readability of a code.
What do you think?

_Same applies for all the Data providers_

File: packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php [hunk 3]
```diff
@@ -2,6 +2,9 @@
 
 namespace Shopsys\FrameworkBundle\Component\Router\FriendlyUrl;
 
+/**
+ * @method FriendlyUrlData createFromIdAndName(int $id, string $name)
```
Comment (grossmannmartin) [inline packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php]: It's to maintain backward compatibility? Can you please mark it somehow, so when we remove deprecations we don't forget to update the interface as this should definitely be part of the interface
(and I don't really know how properly)

File: packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php [hunk 4]
```diff
@@ -54,9 +54,20 @@ public function getFriendlyUrlData(DomainConfig $domainConfig): array
...
+                @trigger_error(
+                    sprintf(
+                        'This approach is deprecated since Shopsys Framework 7.3, implement and use "%s" instead',
+                        FriendlyUrlDataFactoryInterface::class . '::createFromIdAndName()'
+                    ),
+                    E_USER_DEPRECATED
+                );
+                $friendlyUrlData = $this->friendlyUrlDataFactory->create();
+                $friendlyUrlData->id = $data['id'];
+                $friendlyUrlData->name = $data['name'];
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php]: Why don't you use `createFromData` method? You can omit the deprecations here and have it only in `FriendlyUrlDataFactory`

File: packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php (hunk 3 above)
Comment (vitek-rostislav) [reply packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php]: yes, for BC. I believe the @method annotation is sufficient enough - I have added a note to the user story that solves deprecations for 8.0

File: packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php (hunk 4 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php]: I was not able to use it as it is not part of the interface...But your point makes sense, rewritten by adding the @method annotation along with @deprecated sign into the interface :grin:   :+1:

File: packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php (hunk 2 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php]: fair point, fixed

File: packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php [hunk 5]
```diff
@@ -70,4 +74,22 @@ public function getRouteName(): string
...
+    protected function createFriendlyUrlDataDeprecated(array $data): FriendlyUrlData
+    {
+        return $this->friendlyUrlDataFactory->createFromData($data);
+    }
+
+    /**
+     * @param array $data
+     * @return \Shopsys\FrameworkBundle\Component\Router\FriendlyUrl\FriendlyUrlData
+     */
+    protected function createFriendlyUrlDataNewWay(array $data): FriendlyUrlData
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php]: what about `createFriendlyUrlDataNewWay(int $id, string $name): FriendlyUrlData` ?

File: packages/framework/src/Model/Product/Brand/BrandDetailFriendlyUrlDataProvider.php [hunk 6]
```diff
@@ -55,10 +56,13 @@ public function getFriendlyUrlData(DomainConfig $domainConfig): array
 
         $friendlyUrlsData = [];
 
+        $newMethodForDataCreationExists = method_exists($this->friendlyUrlDataFactory, 'createFromIdAndName');
         foreach ($scalarData as $data) {
-            $friendlyUrlData = $this->friendlyUrlDataFactory->create();
-            $friendlyUrlData->name = $data['id'];
-            $friendlyUrlData->id = $data['name'];
+            if ($newMethodForDataCreationExists) {
+                $friendlyUrlData = $this->createFriendlyUrlDataNewWay($data);
```
Comment (grossmannmartin) [inline packages/framework/src/Model/Product/Brand/BrandDetailFriendlyUrlDataProvider.php]: I'm not really sure about the names... Unfortunately I don't have better names...

File: packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php (hunk 5 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/Article/ArticleDetailFriendlyUrlDataProvider.php]: we discussed it - it is not important as the method will be removed in `8.0` (added @internal annotation to ensure that)

File: packages/framework/src/Model/Product/Brand/BrandDetailFriendlyUrlDataProvider.php (hunk 6 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/Product/Brand/BrandDetailFriendlyUrlDataProvider.php]: we discussed it - it is not important as the methods will be removed in `8.0` (added @internal annotation to ensure that)

File: packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php (hunk 3 above)
Comment (PetrHeinz) [inline packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php]: Please add a note about this into *US-6091 Resolving of deprecations for v8.0.0* in our internal backlog, I'm bit worried the method would not be added into the interface otherwise.

Comment (vitek-rostislav) [reply packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php]: I have already added a note there that it is necessary to resolve `@method` and `@internal` annotations, is it sufficient?

File: packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFactoryInterface.php [hunk 7]
```diff
@@ -2,7 +2,7 @@
 
 namespace Shopsys\FrameworkBundle\Component\Router\FriendlyUrl;
 
-interface FriendlyUrlFactoryInterface
+interface   FriendlyUrlFactoryInterface
```
Comment (PetrHeinz) [inline packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFactoryInterface.php]:
```suggestion
interface FriendlyUrlFactoryInterface
```

File: packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php (hunk 3 above)
Comment (PetrHeinz) [reply packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactoryInterface.php]: Well this is the only `@method` that needs any kind of resolving, but fine
