### PR TITLE
[framework] fixed sending emails with attachment

### LINKED ISSUE #805: Check functionality of Swift_Mailer, Swift_Attachment, Flysystem
### What is happening

There are rumors that swift_attachment especially for mail templates doesn't want to work with Flysystem implementation.

### Expected result

To have readyToUse flysystem with Swift_Attachment

### LINKED ISSUE #858: E-mail attachment on CI
### What is happening

When I upload an e-mail attachment to the e-mail templates and send the e-mail with the attachment, the e-mail is not delivered. (Reporetd by Partik Bajer)

### Expected result
Please fix it.

### PR DESCRIPTION
**Pull request by grossmannmartin**
| Q             | A
| ------------- | ---
|Description, reason for the PR| E-mails with attachment(s) was not sent. This is fixed now.
|New feature| No 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No (used setter injection) 
|Fixes issues| closes #858, closes #805 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/Model/Mail/MailTemplateAttachmentFilepathProvider.php [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+    /**
+     * @param \Shopsys\FrameworkBundle\Component\UploadedFile\UploadedFile $uploadedFile
+     * @return string
+     */
+    public function getTemporaryFilepath(UploadedFile $uploadedFile): string
+    {
+        $temporaryFilepath = TransformString::removeDriveLetterFromPath($this->fileUpload->getTemporaryFilepath($uploadedFile->getFilename()));
+
+        if (!$this->mountManager->has('local://' . $temporaryFilepath)) {
```
Comment (boris-brtan) [inline packages/framework/src/Model/Mail/MailTemplateAttachmentFilepathProvider.php]: hi, how long will be the attachement cached?

Comment (grossmannmartin) [reply packages/framework/src/Model/Mail/MailTemplateAttachmentFilepathProvider.php]: Hi, the name is unique for all added attachments
