### PR TITLE
[shopsys] fix issues with QueryBuilderExtender's method AddOrExtendJoin

### LINKED ISSUE #997: ProductFilterRepository - error in queryBuilder (addOrExtendJoin)
### What is happening
[Semantical Error] line 0, col 584 near ‘pcp WITH pcp.product’: Error: ‘pcp’ is already defined.

Nothing special about my settings

Problem is caused by extended ProductCalculatedPrice model. Function addOrExtendJoin in ProductFilterRepository checks ShopBundle/ProductCalculatedPrice against Framework/ProductCalculatedPrice. 

### Expected result

There should be some class resolver as you have on other places in code, or there should be used interface.

### PR DESCRIPTION
**Pull request by pk16011990**
| Q             | A
| ------------- | ---
|Description, reason for the PR| there are problems with QueryBuilderExtender's method AddOrExtendJoin 
|New feature| No 
|[BC breaks](https://github.com/shopsys/shopsys/blob/master/docs/contributing/backward-compatibility-promise.md)| No 
|Fixes issues| closes #997  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

- [x] fix AddOrExtendJoin then creating first join
- [x] fix AddOrExtendJoin when you try to extend framework's class with extended class
- [x] add test for first issue
- [x] add unit test for second issue
- [x] add functional test for second issue

### CODE REVIEW

File: project-base/tests/ShopBundle/Functional/Component/Doctrine/QueryBuilderExtenderTest.php [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        $queryBuilderExtender->addOrExtendJoin($queryBuilder, $secondJoinedEntity, 'p', '0 = 0');
+
+        $joinDqlPart = $queryBuilder->getDQLPart('join');
+        $this->assertCount(1, reset($joinDqlPart));
+    }
+
+    /**
+     * @return array
+     */
+    public function extendJoinWithExtendedEntityProvider(): array
```
Comment (PetrHeinz) [inline project-base/tests/ShopBundle/Functional/Component/Doctrine/QueryBuilderExtenderTest.php]: Wouldn't a data provider be a cleaner choice? You could also check the obvious `Category x Category` and `BaseCategory x BaseCategory`...

File: packages/framework/src/Component/Doctrine/QueryBuilderExtender.php [hunk 2]
```diff
@@ -58,4 +90,20 @@ protected function getRootAlias(QueryBuilder $queryBuilder)
 
         return $firstAlias;
     }
+
+    /**
+     * @param \Doctrine\ORM\QueryBuilder $queryBuilder
+     * @return array
```
Comment (PetrHeinz) [inline packages/framework/src/Component/Doctrine/QueryBuilderExtender.php]:
```suggestion
     * @return \Doctrine\ORM\Query\Expr\Join[]
```

File: packages/framework/src/Component/Doctrine/QueryBuilderExtender.php [hunk 3]
```diff
@@ -18,21 +49,22 @@ class QueryBuilderExtender
...
     {
-        $rootAlias = $this->getRootAlias($queryBuilder);
+        $joins = $this->getJoinsFromQueryBuilder($queryBuilder);
 
         $joinAlreadyUsed = false;
-
-        foreach ($queryBuilder->getDQLPart('join')[$rootAlias] as $join) {
+        $resolvedClass = $this->entityNameResolver->resolve($class);
+        foreach ($joins as $join) {
             /* @var $join \Doctrine\ORM\Query\Expr\Join */
```
Comment (PetrHeinz) [inline packages/framework/src/Component/Doctrine/QueryBuilderExtender.php]: Can be deleted if return value of `getJoinsFromQueryBuilder` is annotated
```suggestion
```

File: project-base/tests/ShopBundle/Functional/Component/Doctrine/QueryBuilderExtenderTest.php [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+     * @param string $expectedJoinedEntity
+     */
+    public function testExtendJoinWithExtendedEntity(
+        string $firstJoinedEntity,
+        string $secondJoinedEntity,
+        string $expectedJoinedEntity
+    ): void {
+        /** @var \Shopsys\FrameworkBundle\Component\Doctrine\QueryBuilderExtender $queryBuilderExtender */
+        $queryBuilderExtender = $this->getContainer()->get(QueryBuilderExtender::class);
+        /** @var \Doctrine\ORM\EntityManager $em */
```
Comment (PetrHeinz) [inline project-base/tests/ShopBundle/Functional/Component/Doctrine/QueryBuilderExtenderTest.php]:
```suggestion
        /** @var \Doctrine\ORM\EntityManagerInterface $em */
```

**Comment by pk16011990** [comment]
Hi, 

when can I expect reaction/merge?

File: packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+namespace Tests\FrameworkBundle\Unit\Component\Doctrine;
+
+use Doctrine\ORM\EntityManagerInterface;
+use Doctrine\ORM\QueryBuilder;
+use PHPUnit\Framework\TestCase;
+use Shopsys\FrameworkBundle\Component\Doctrine\QueryBuilderExtender;
+use Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver;
+use Shopsys\FrameworkBundle\Model\Category\Category;
+use Shopsys\FrameworkBundle\Model\Product\Product as BaseProduct;
+use Shopsys\ShopBundle\Model\Product\Product;
```
Comment (s3tezsky) [inline packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php]: Sadly this will not work from `shopsys/framework`.

I would suggest to create new extended class of `Product` as a fixture for tests only. The similar way how it is done for testing elasticsearch https://github.com/shopsys/shopsys/blob/master/packages/framework/tests/Unit/Component/Elasticsearch/__fixtures/CategoryIndex.php

File: packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+        $entityNameResolver = new EntityNameResolver($extensionMap);
+        $queryBuilderExtender = new QueryBuilderExtender($entityNameResolver);
+        $queryBuilder
+            ->select('c')
+            ->from(Category::class, 'c');
+        $queryBuilderExtender->addOrExtendJoin($queryBuilder, $firstJoinedEntity, 'p', '0 = 0');
+        $queryBuilderExtender->addOrExtendJoin($queryBuilder, $secondJoinedEntity, 'p', '1 = 1');
+
+        $dql = $queryBuilder->getDQL();
+        $this->assertSame('SELECT c FROM ' . Category::class . ' c INNER JOIN ' . $expectedJoinedEntity . ' p WITH 0 = 0 WHERE 1 = 1', $dql);
```
Comment (s3tezsky) [inline packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php]: _Nitpick:_ I would rather use `sprintf()` here
