### PR TITLE
[framework] fixed clearing form options in product picker

### LINKED ISSUE #1187: Allowed choice of variant product in product picker window after search with not allowed variants
### What is happening
I use `Shopsys\FrameworkBundle\Form\ProductsType` in form with option `allow_variants` set to `false`.

So when I open products picker window, I can't choose variant - it is correct behavior.

But when I use search in that same product picker window, I can choose variant from searched results - it is not correct behavior, because I set `allow_variants` to `false`.

### Expected result
I can't choose variant product after use search in product picker window (with using `ProductsType` with option `allow_variants` set to `false`).

### PR DESCRIPTION
**Pull request by s3tezsky**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Fixes linked issue
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #1187 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/Controller/Admin/ProductPickerController.php [hunk 1]
```diff
@@ -63,12 +63,18 @@ public function __construct(
...
-     * @Route("/product-picker/pick-multiple/{jsInstanceId}/")
+     * @Route("/product-picker/pick-multiple/{jsInstanceId}/{allowMainVariants}/{allowVariants}")
      * @param \Symfony\Component\HttpFoundation\Request $request
      * @param string $jsInstanceId
+     * @param bool $allowMainVariants
+     * @param bool $allowVariants
      */
-    public function pickMultipleAction(Request $request, $jsInstanceId)
-    {
+    public function pickMultipleAction(
```
Comment (TomasLudvik) [inline packages/framework/src/Controller/Admin/ProductPickerController.php:72]: This will not work with strict_types = 1, you are right now changing type, please update it

Comment (s3tezsky) [reply packages/framework/src/Controller/Admin/ProductPickerController.php:72]: eh? I do not understaand this. What type am I changing?

On other hand here is not used `strict_types=1`.

Comment (s3tezsky) [reply packages/framework/src/Controller/Admin/ProductPickerController.php:72]: Actually even with strict_types it workl like a charm. I am leaving it as is.

Comment (TomasLudvik) [reply packages/framework/src/Controller/Admin/ProductPickerController.php:72]: ok
