### PR TITLE
[shopsys] prevent to pass null to not-nullable argument to ListedProductViewFactory::createFromArray()

### LINKED ISSUE #2098: Passing nullable value to required argument in ListedProductViewFactory.php
Found in https://github.com/shopsys/shopsys/pull/2090#discussion_r512077387

### What is happening

When creating `ListedProductView` there may be passed `null` (actually it cannot, because of our recalculations and so on) to argument requiring `ProductPrice`.

https://github.com/shopsys/shopsys/blob/0d77eb9c5e6309df3e91eeaacf60b3c20419e784/packages/read-model/src/Product/Listed/ListedProductViewFactory.php#L127

### Expected result

The edgecase without found price is handled properly.

_E.g.: There could be raised and hadled exception when the `ProductPrice` is not available instead of returning null._

### PR DESCRIPTION
**Pull request by s3tezsky**
| Q             | A
| ------------- | ---
|Description, reason for the PR| See linked issue
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| fixes #2098  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/read-model/src/Product/Listed/ListedProductViewFactory.php [hunk 1]
```diff
@@ -144,12 +145,20 @@ public function createFromProduct(Product $product, ?ImageView $imageView, Produ
      */
     public function createFromArray(array $productArray, ?ImageView $imageView, ProductActionView $productActionView, PricingGroup $pricingGroup): ListedProductView
     {
+        $productPrice = $this->priceFactory->createProductPriceFromArrayByPricingGroup(
+            $productArray['prices'],
+            $pricingGroup
+        );
+        if ($productPrice === null) {
+            throw new NoProductPriceForPricingGroupException($productArray['id'], $pricingGroup->getId());
```
Comment (grossmannmartin) [inline packages/read-model/src/Product/Listed/ListedProductViewFactory.php:153]: I'm thinking about throwing this exception directly in the factory. Because from a create method I expect creating an object and not return null. What do you think?

File: packages/read-model/src/Product/Listed/ListedProductViewFactory.php [hunk 2]
```diff
@@ -144,12 +145,20 @@ public function createFromProduct(Product $product, ?ImageView $imageView, Produ
      */
     public function createFromArray(array $productArray, ?ImageView $imageView, ProductActionView $productActionView, PricingGroup $pricingGroup): ListedProductView
     {
+        $productPrice = $this->priceFactory->createProductPriceFromArrayByPricingGroup(
```
Comment (grossmannmartin) [inline packages/read-model/src/Product/Listed/ListedProductViewFactory.php:148]: can you please add deprecation notice into method `createProductPriceFromArrayByPricingGroup` when trying to return null as we discussed?

File: packages/read-model/src/Product/Listed/ListedProductViewFactory.php (hunk 1 above)
Comment (s3tezsky) [reply packages/read-model/src/Product/Listed/ListedProductViewFactory.php:153]: I agree but we cannot do it in minor version as discussed.

File: packages/read-model/src/Product/Listed/ListedProductViewFactory.php (hunk 2 above)
Comment (s3tezsky) [reply packages/read-model/src/Product/Listed/ListedProductViewFactory.php:148]: Sure. It has been done in 822e9bbdbf1f19011910b9675d4b963e2d785040

File: packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php [hunk 3]
```diff
@@ -269,12 +270,16 @@ protected function createFromArray(array $productsArray): array
...
-            );
+            try {
+                $listedProductViews[$productId] = $this->listedProductViewFactory->createFromArray(
+                    $productArray,
+                    $imageViews[$productId],
+                    $this->productActionViewFactory->createFromArray($productArray),
+                    $this->currentCustomerUser->getPricingGroup()
+                );
+            } catch (NoProductPriceForPricingGroupException $exception) {
+                continue;
```
Comment (grossmannmartin) [inline packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php:281]: I got feedback on this line – silently dropped exceptions can be confusing when you're solving some unexpected behavior. 
I'm not really sure how to deal with this information.

**Review by grossmannmartin — APPROVED** [review]

**Review by sslt — APPROVED** [review]
