### PR TITLE
whole application now correctly reflects input price type settings

### LINKED ISSUE #2684: PricingSetting::INPUT_PRICE_TYPE is not respected on several places
## Describe the bug
The application allows us to choose the input price type (it can be set in the admnistration `admin/superadmin/pricing/`). However, when I start using `INPUT_PRICE_TYPE_WITHOUT_VAT` (typical for B2B stores), I can see several issues:

- `QuantifiedProductPriceCalculation::calculatePrice` has hardcoded price calculation from price with VAT, which might result in the wrong results - the customer might see badly calculated prices without VAT in the cart 
- the same applies to `OrderItemPriceCalculation` - the customer then sees badly calculated prices of order items in order mail and on the order detail page. Also, the administrator sees the bad prices.

I tried to simulate the problem on the current master version of SSFWCC:
- I set the input price to "Without VAT"
- I created a new VAT with a 19 % rate and set it as default for the SK domain 
- I set the SK domain price for Hello Kitty to 5,80 €
- On the SK domain, I put Hello Kitty in the cart, and change the quantity to 3 pcs. One of the problems is (rather UX), I can not see the total price without VAT...However, if it was possible to see it, I would see it is badly calculated to 17,39 € (while it should be 3 x 5,80 = 17,4 €)
- After finishing the order, I can see the item's bad prices in administration (see image 1)
- Also, the order detail on SF is quite weird (see image 2) - the total price without VAT is wrong and the first column with unit price without VAT is labeled as "Unit price with VAT"

**Image 1:**
Screenshot from 2023-07-28 15-10-39

**Image 2:**
Screenshot (3)

### PR DESCRIPTION
**Pull request by TomasLudvik**
#### Description, the reason for the PR
- calculation of prices for input price type without VAT has been slightly changed
- manual setting of order item prices is now done in price without VAT for input price without VAT setting
- setting of order limit and discount amount for promo codes is now done in price without VAT for input price without VAT setting
- setting of free transport and payment limit is now done in price without VAT for input price without VAT setting

#### Fixes issues
closes #2684 

#### License Agreement for contributions

- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

## Summary by CodeRabbit

- **New Features**
  - Introduced a configurable pricing engine that dynamically handles prices with or without tax, adapting calculations based on currency settings.
- **Improvements**
  - Enhanced the accuracy and consistency of order totals, discount computations, and free transport/payment thresholds.
  - Streamlined data presentation in the storefront and API responses for clearer communication of pricing details.

These updates ensure a more reliable and transparent pricing experience for end users.

----
:globe_with_meridians: Live Preview:
  - https://tl-input-price-refactoring.odin.shopsys.cloud
  - https://cz.tl-input-price-refactoring.odin.shopsys.cloud

### CODE REVIEW

**Comment by vitek-rostislav** [comment]
@coderabbitai review

File: packages/framework/src/Model/Pricing/BasePriceCalculation.php [hunk 1]
```diff
@@ -28,41 +28,26 @@ public function __construct(
      * @param \Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency $currency
      * @return \Shopsys\FrameworkBundle\Model\Pricing\PriceInterface
      */
-    public function calculateBasePriceRoundedByCurrency(
+    public function calculateRoundedBasePrice(
```
Comment (vitek-rostislav) [inline packages/framework/src/Model/Pricing/BasePriceCalculation.php:31]: I have a feeling that the method name could remain the same, that would mean one BC break less, but I understand if you do not want to change it back :smile: But let's discuss it please

File: packages/framework/src/Model/Order/Item/OrderItemPriceCalculation.php [hunk 2]
```diff
@@ -31,15 +39,34 @@ public function __construct(
      * @param int $domainId
      * @return \Shopsys\FrameworkBundle\Component\Money\Money
      */
-    public function calculatePriceWithoutVat(OrderItemData $orderItemData, int $domainId): Money
```
Comment (vitek-rostislav) [inline packages/framework/src/Model/Order/Item/OrderItemPriceCalculation.php:34]: maybe this method could also remain the same, and the decision could be made inside (the two new methods could be protected then), or? It would simplify the usage imho

File: packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig [hunk 3]
```diff
@@ -18,9 +18,19 @@
...
-        </td>
+
+        {% if inputPriceType is same as(constant('Shopsys\\FrameworkBundle\\Model\\Pricing\\PricingSetting::INPUT_PRICE_TYPE_WITH_VAT')) %}
+            <td class="text-right">
+                {{ self.inputPriceWidget(orderItemForm.unitPriceWithVat) }}
+            </td>
+            <td class="text-right">{{ self.calculablePriceWidget(orderItemForm.unitPriceWithoutVat) }}</td>
+        {% elseif inputPriceType is same as(constant('Shopsys\\FrameworkBundle\\Model\\Pricing\\PricingSetting::INPUT_PRICE_TYPE_WITHOUT_VAT')) %}
+            <td class="text-right">
+                {{ self.calculablePriceWidget(orderItemForm.unitPriceWithVat) }}
```
Comment (vitek-rostislav) [inline packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig:29]: `unitPriceWithVat` should be used here always?

File: packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig [hunk 4]
```diff
@@ -58,7 +67,19 @@
...
-        <td class="text-right">{{ self.priceWithVatWidget(orderTransportForm.unitPriceWithVat) }}</td>
+
+        {% if inputPriceType is same as(constant('Shopsys\\FrameworkBundle\\Model\\Pricing\\PricingSetting::INPUT_PRICE_TYPE_WITH_VAT')) %}
+            <td class="text-right">
+                {{ self.inputPriceWidget(orderTransportForm.unitPriceWithVat) }}
+            </td>
+            <td class="text-right">{{ self.calculablePriceWidget(orderTransportForm.unitPriceWithoutVat) }}</td>
+        {% elseif inputPriceType is same as(constant('Shopsys\\FrameworkBundle\\Model\\Pricing\\PricingSetting::INPUT_PRICE_TYPE_WITHOUT_VAT')) %}
+            <td class="text-right">
+                {{ self.calculablePriceWidget(orderTransportForm.unitPriceWithVat) }}
```
Comment (vitek-rostislav) [inline packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig:78]: unitPriceWithVat should be used here always?

File: packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig [hunk 5]
```diff
@@ -87,7 +107,19 @@
...
-        <td class="text-right">{{ self.priceWithVatWidget(orderPaymentForm.unitPriceWithVat) }}</td>
+
+        {% if inputPriceType is same as(constant('Shopsys\\FrameworkBundle\\Model\\Pricing\\PricingSetting::INPUT_PRICE_TYPE_WITH_VAT')) %}
+            <td class="text-right">
+                {{ self.inputPriceWidget(orderPaymentForm.unitPriceWithVat) }}
+            </td>
+            <td class="text-right">{{ self.calculablePriceWidget(orderPaymentForm.unitPriceWithoutVat) }}</td>
+        {% elseif inputPriceType is same as(constant('Shopsys\\FrameworkBundle\\Model\\Pricing\\PricingSetting::INPUT_PRICE_TYPE_WITHOUT_VAT')) %}
+            <td class="text-right">
+                {{ self.calculablePriceWidget(orderPaymentForm.unitPriceWithVat) }}
```
Comment (vitek-rostislav) [inline packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig:118]: unitPriceWithVat should be used here always?

File: packages/framework/src/Model/Pricing/Rounding.php [hunk 6]
```diff
@@ -36,19 +36,21 @@ public function roundPriceWithVatByCurrency(Money $priceWithVat, Currency $curre
...
     /**
      * @param \Shopsys\FrameworkBundle\Component\Money\Money $vatAmount
+     * @param \Shopsys\FrameworkBundle\Model\Pricing\Currency\Currency $currency
      * @return \Shopsys\FrameworkBundle\Component\Money\Money
      */
-    public function roundVatAmount(Money $vatAmount): Money
+    public function roundVatAmount(Money $vatAmount, Currency $currency): Money
     {
-        return $vatAmount->round(2);
+        return $vatAmount->round($currency->getRoundingPlacesPriceWithoutVat());
```
Comment (vitek-rostislav) [inline packages/framework/src/Model/Pricing/Rounding.php:54]: I am wondering whether this should be mentioned in the setting itself or it is an implementation detail - my point is that the admin thinks he sets the places for rounding the price with vat but internally, he also sets the places for VAT rounding, right?

File: project-base/app/tests/App/Functional/Component/EntityLog/EntityLogTest.php [hunk 7]
```diff
@@ -90,6 +90,11 @@ class EntityLogTest extends TransactionFunctionalTestCase
      */
     private PriceConverter $priceConverter;
 
+    protected function setUp(): void
+    {
+        parent::setUp();
+    }
+
```
Comment (vitek-rostislav) [inline project-base/app/tests/App/Functional/Component/EntityLog/EntityLogTest.php]: this is not necessary

File: project-base/app/tests/App/Functional/Model/Order/OrderFacadeEditTest.php [hunk 8]
```diff
@@ -45,6 +45,7 @@ protected function setUp(): void
     {
         parent::setUp();
 
+        $this->setInputPriceTypeToInputPriceTypeWithVat();
```
Comment (vitek-rostislav) [inline project-base/app/tests/App/Functional/Model/Order/OrderFacadeEditTest.php]: do not we want another test for input price type without VAT?

File: project-base/app/tests/App/Functional/Model/Pricing/RelevantSpecialPriceForProductTest.php [hunk 9]
```diff
@@ -51,6 +51,13 @@ final class RelevantSpecialPriceForProductTest extends TransactionFunctionalTest
      */
     private readonly PriceListFacade $priceListFacade;
 
+    protected function setUp(): void
+    {
+        parent::setUp();
+
+        $this->setInputPriceTypeToInputPriceTypeWithVat();
```
Comment (vitek-rostislav) [inline project-base/app/tests/App/Functional/Model/Pricing/RelevantSpecialPriceForProductTest.php]: do not we want another test for input price type without VAT?

File: packages/framework/src/Migrations/Version20250303130234.php [hunk 10]
```diff
@@ -0,0 +1,28 @@
...
+use Shopsys\MigrationBundle\Component\Doctrine\Migrations\AbstractMigration;
+
+class Version20250303130234 extends AbstractMigration
+{
+    /**
+     * @param \Doctrine\DBAL\Schema\Schema $schema
+     */
+    public function up(Schema $schema): void
+    {
+        $this->sql('ALTER TABLE promo_code_limit DROP CONSTRAINT promo_code_limit_pkey');
```
Comment (vitek-rostislav) [inline packages/framework/src/Migrations/Version20250303130234.php:19]: do not we want that constraint anymore? It is covered by that new primary key, right?

File: packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/ApplyNominalPromoCodeMiddleware.php [hunk 11]
```diff
@@ -93,14 +95,14 @@ public function createAndAddOrderItemData(
...
-     * @param \Shopsys\FrameworkBundle\Component\Money\Money $totalApplicableProductsPriceAmountWithVat
+     * @param \Shopsys\FrameworkBundle\Model\Pricing\PriceInterface $totalApplicableProductsPrice
      * @return \Shopsys\FrameworkBundle\Model\Order\Item\OrderItemData|null
      */
     protected function createDiscountOrderItemData(
         PromoCode $promoCode,
         PromoCodeLimit $promoCodeLimit,
         DomainConfig $domainConfig,
-        Money $totalApplicableProductsPriceAmountWithVat,
+        PriceInterface $totalApplicableProductsPrice,
```
Comment (vitek-rostislav) [inline packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/ApplyNominalPromoCodeMiddleware.php:105]: this change should be mentioned in the upgrade notes IMHO

File: packages/framework/src/Model/TransportAndPayment/FreeTransportAndPaymentFacade.php [hunk 12]
```diff
@@ -40,12 +40,12 @@ public function isActive(int $domainId, bool $forceFreeTransportAndPayment): boo
...
 
     /**
-     * @param \Shopsys\FrameworkBundle\Component\Money\Money $productsPriceWithVat
+     * @param \Shopsys\FrameworkBundle\Model\Pricing\PriceInterface $productsPrice
      * @param int $domainId
      * @param bool $forceFreeTransportAndPayment
      * @return bool
      */
-    public function isFree(Money $productsPriceWithVat, int $domainId, bool $forceFreeTransportAndPayment): bool
+    public function isFree(PriceInterface $productsPrice, int $domainId, bool $forceFreeTransportAndPayment): bool
```
Comment (vitek-rostislav) [inline packages/framework/src/Model/TransportAndPayment/FreeTransportAndPaymentFacade.php:48]: this should be mentioned in the upgrade notes IMHO

**Review by vitek-rostislav — CHANGES_REQUESTED** [review]
Excellent job there, love it :tophat: :ok_hand:

File: packages/framework/src/Model/Pricing/BasePriceCalculation.php (hunk 1 above)
Comment (TomasLudvik) [reply packages/framework/src/Model/Pricing/BasePriceCalculation.php:31]: For me this change is a must. I think the naming was misleading, as only price with VAT is rounded by currency, but price without VAT is not.

File: packages/framework/src/Model/Order/Item/OrderItemPriceCalculation.php (hunk 2 above)
Comment (TomasLudvik) [reply packages/framework/src/Model/Order/Item/OrderItemPriceCalculation.php:34]: This class is trying to be as easiest for slight change in calculations, that I wanted to keep that - I started with merging all those small methods into one as I didnt see the need for that, but then I realized that and keep the code splitted in as many small parts as possible.

File: packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig (hunk 3 above)
Comment (TomasLudvik) [reply packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig:29]: I do not understand the question. `calculablePriceWidget` and `inputPriceWidget` are changing by INPUT_PRICE_TYPE here.

File: packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig (hunk 4 above)
Comment (TomasLudvik) [reply packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig:78]: I do not understand the question. `calculablePriceWidget` and `inputPriceWidget` are changing by INPUT_PRICE_TYPE here.

File: packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig (hunk 5 above)
Comment (TomasLudvik) [reply packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig:118]: I do not understand the question. `calculablePriceWidget` and `inputPriceWidget` are changing by INPUT_PRICE_TYPE here.

File: packages/framework/src/Model/Pricing/Rounding.php (hunk 6 above)
Comment (TomasLudvik) [reply packages/framework/src/Model/Pricing/Rounding.php:54]: The setting is for price without VAT. I felt logical, that if this price can have 10 decimal places, then VAT amount should have same setting. Do you disagree?

File: packages/framework/src/Migrations/Version20250303130234.php (hunk 10 above)
Comment (TomasLudvik) [reply packages/framework/src/Migrations/Version20250303130234.php:19]: Yes

File: project-base/app/tests/App/Functional/Model/Order/OrderFacadeEditTest.php (hunk 8 above)
Comment (TomasLudvik) [reply project-base/app/tests/App/Functional/Model/Order/OrderFacadeEditTest.php]: I did not feel the need, do you?

File: project-base/app/tests/App/Functional/Model/Pricing/RelevantSpecialPriceForProductTest.php (hunk 9 above)
Comment (TomasLudvik) [reply project-base/app/tests/App/Functional/Model/Pricing/RelevantSpecialPriceForProductTest.php]: I did not feel the need, do you?

File: packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/ApplyNominalPromoCodeMiddleware.php (hunk 11 above)
Comment (TomasLudvik) [reply packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/ApplyNominalPromoCodeMiddleware.php:105]: I thought we no longer mention changes in method interfaces as those are reported by coding standards.

File: packages/framework/src/Model/TransportAndPayment/FreeTransportAndPaymentFacade.php (hunk 12 above)
Comment (TomasLudvik) [reply packages/framework/src/Model/TransportAndPayment/FreeTransportAndPaymentFacade.php:48]: I thought we no longer mention changes in method interfaces as those are reported by coding standards.

File: packages/framework/src/Model/Pricing/BasePriceCalculation.php (hunk 1 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/Pricing/BasePriceCalculation.php:31]: ok, let's keep it as is

**Review by vitek-rostislav — APPROVED** [review]
