### PR TITLE
access control and admin menu tweaks

### LINKED ISSUE #3249: Refactoring SideMenuConfigurationSubscriber and MenuItemsGrantedRolesSetting
Hello,

I would like to propose a refactoring of the SideMenuConfigurationSubscriber->removeNotGrantedItemsFromMenu and MenuItemsGrantedRolesSetting::getGrantedRolesByMenuItems() functionalities. Currently, the architecture is prone to errors, making it easy for developers to make mistakes. For instance:

`'nomenclatures' . self::MENU_ITEM_PATH_SEPARATOR . 'statusLists' . self::MENU_ITEM_PATH_SEPARATOR . 'pulled_statuses'`

instead of

`'nomenclatures' . self::MENU_ITEM_PATH_SEPARATOR . 'statusLists' . self::MENU_ITEM_PATH_SEPARATOR . 'pulled_status_list'`

There is no alert or exception thrown to indicate that something does not exist. This can lead to confusion, especially if the some section is mistaken for another, or if changes are not updated after moves (when moving menu items between sections).

And some of strings could be in constants to be easily found or changed. Or there could be a single method to concatenate these strings together.

Ideally, getPagesGrantedRoles() should be in the same place as the menu item definitions.

Thank you for considering this request.

Pavel

### PR DESCRIPTION
**Pull request by vitek-rostislav**
#### Description, the reason for the PR
1. Security settings for role hierarchy is moved from `security.yaml` into the new `security.php` config that allows developers to use PHP constants from `Roles` classes instead of copy-pasting the string values
2. The access control security setting was also moved from `security.yaml` into the new `security.php` config. Moreover, the access control rules are now defined using new `#[AccessControlRule]` attribute that is defined under a controller's action methods and is therefore bound to a particular route instead of the path patterns, e.g.:
```
    #[Route(path: '/stock/list/')]
    #[AccessControlRule([Roles::ROLE_STOCK_VIEW])]
    public function listAction(): Response
```
3. Added a new `shopsys:check-access-control-rules` command under `standards` phing targets that checks that all routes are covered by access control rules
4. `MenuItemsGrantedRolesSetting` was removed along with the necessity to manually configure the allowed menu sections for particular roles. Instead, `MenuItemsGrantedRolesSubscriber` now leverages the dynamic access control setting and automatically removes the not granted items from menu.
5. added missing roles for closed days agenda
6. `SideMenuBuilder` now uses constants for the menu item names to ease the menu extensibility from a project
7. Simplified adding new roles on a project by implementing helper methods in `Roles` class + extended docs for adding a new admin page to cover adding new roles

**TLDR;** So what is now needed when adding new roles on a project? Well:

image

image

#### Fixes issues
closes #3249

#### License Agreement for contributions

- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

----
:globe_with_meridians: Live Preview:
  - https://rv-menu.odin.shopsys.cloud
  - https://cz.rv-menu.odin.shopsys.cloud

### CODE REVIEW

File: project-base/app/config/packages/security.php [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+
+/**
+ * @return \Shopsys\FrameworkBundle\Model\Security\AccessControl\RouteAccessControlData[]
+ */
+function getRouteAccessControlRules(): array
+{
+    $accessControlCacheFile = sprintf(__DIR__ . '/../../var/cache/%s/access_control_rules.json', Environment::getEnvironment());
+
+    if (file_exists($accessControlCacheFile)) {
+        $accessControlRulesArray = json_decode(file_get_contents($accessControlCacheFile), true, 512, JSON_THROW_ON_ERROR);
```
Comment (grossmannmartin) [inline project-base/app/config/packages/security.php]: What about using the PHP file instead of getting content + JSON decoding? 
Then we can just use `$accessControlRulesArray = require $accessControlCacheFile`

File: project-base/app/config/packages/security.php [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+        $routeAccessControlRules = [];
+        foreach ($accessControlRulesArray as $accessControlRuleArray) {
+            $routeAccessControlRules[] = RouteAccessControlData::fromJson($accessControlRuleArray);
+        }
```
Comment (grossmannmartin) [inline project-base/app/config/packages/security.php]: is it `fromJson`? It seems more like `fromArray`

File: packages/framework/src/Model/AdminNavigation/MenuItemsGrantedRolesSubscriber.php [hunk 3]
```diff
@@ -37,40 +42,106 @@ public static function getSubscribedEvents(): array
     public function removeNotGrantedItemsFromMenu(ConfigureMenuEvent $event): void
     {
         $rootMenu = $event->getMenu();
+        $this->removeNotGrantedItems($rootMenu);
+    }
```
Comment (grossmannmartin) [inline packages/framework/src/Model/AdminNavigation/MenuItemsGrantedRolesSubscriber.php:46]: Is the separation into another method worth it here?

File: packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php [hunk 4]
```diff
@@ -7,22 +7,192 @@
...
+    public const string CSS_DOCS = 'css_docs';
+    public const string LIST_URL = 'urls';
+    public const string MAIL_WHITELIST = 'mail_whitelist';
+    public const string CLEAR_STOREFRONT_CACHE = 'clear_storefront_cache';
+    public const string CSP_HEADER = 'cspHeader';
+    public const string ROOT_INTEGRATIONS = 'integrations';
+    public const string LIST_FEED = 'feeds';
+    public const string SETION_HEUREKA = 'heureka';
+    public const string HEUREKA_SETTINGS = 'settings';
+
```
Comment (grossmannmartin) [inline packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php:187]: I'm just thinking. What about a little unification? 
We currently have several constants with the `new`, `edit`, ...

**Review by grossmannmartin — CHANGES_REQUESTED** [review]

File: packages/framework/src/Model/AdminNavigation/MenuItemsGrantedRolesSubscriber.php (hunk 3 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/AdminNavigation/MenuItemsGrantedRolesSubscriber.php:46]: it is because of the recursion, we can discuss it :slightly_smiling_face:

File: packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php (hunk 4 above)
Comment (vitek-rostislav) [reply packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php:187]: I did not want to rename the sections as I was afraid of unnecessary BC breaks. Also, it felt like there is not way of unifying it without renaming, however, let's talk about it :slightly_smiling_face:

File: project-base/app/config/packages/security.php (hunk 1 above)
Comment (vitek-rostislav) [reply project-base/app/config/packages/security.php]: interesting idea, I tried it as you suggested, however, it would probably need additional implementation of `__set_state` method for `AccessControlRule`? Let's talk about it :slightly_smiling_face:

File: project-base/app/config/packages/security.php (hunk 2 above)
Comment (vitek-rostislav) [reply project-base/app/config/packages/security.php]: true indeed. 1a617327d8

File: docs/cookbook/adding-a-new-administration-page.md [hunk 5]
```diff
@@ -115,6 +114,78 @@ The event subscriber should be auto-discovered by Symfony, reconfiguring the men
 
 ![Dashboard admin menu after the modification](img/dashboard-menu-after.png)
 
+## Access control
+
+When adding a new administrator page, you need to decide which [administrator roles](../administration/admin-rights.md) should have access to it.
+For the new agenda, you will probably need to create a new role. Usually, a `VIEW`/`FULL` pair of roles is used, so let's follow the convention here as well. In `Roles.php`, add the new roles, define theirs translations, and put them into the hierarchy:
+
+```diff
```
Comment (grossmannmartin) [inline docs/cookbook/adding-a-new-administration-page.md]: Almost all content here is added text. What about using `php` instead of `diff`? I think it's a little more clear when reading

File: docs/cookbook/adding-a-new-administration-page.md [hunk 6]
```diff
@@ -115,6 +114,78 @@ The event subscriber should be auto-discovered by Symfony, reconfiguring the men
...
++    #[Override]
++    public static function getRolesHierarchy(): array
++    {
++        $rolesHierarchy = parent::getRolesHierarchy();
++
++        $rolesHierarchy[static::ROLE_ALL][] = static::ROLE_X_FULL;
++        $rolesHierarchy[static::ROLE_ALL_VIEW][] = static::ROLE_X_VIEW;
++        $rolesHierarchy[static::ROLE_X_FULL] = [static::ROLE_X_VIEW];
++
++        return $rolesHierarchy;
```
Comment (grossmannmartin) [inline docs/cookbook/adding-a-new-administration-page.md]: Please don't hate me :D 

What about making it more like a configuration? 
I'm thinking about something like 

```php
protected static function configureAdditionalRoles(): void {
    self::addRolePair(viewRole: static::ROLE_X_VIEW, fullRole: static::ROLE_X_FULL)
}
```

then it would be much more readable in my opinion. What do you think?

**Review by grossmannmartin — APPROVED** [review]

File: docs/cookbook/adding-a-new-administration-page.md (hunk 6 above)
Comment (vitek-rostislav) [reply docs/cookbook/adding-a-new-administration-page.md]: That is a great idea, what about this? fd487c8c43

File: docs/cookbook/adding-a-new-administration-page.md (hunk 5 above)
Comment (vitek-rostislav) [reply docs/cookbook/adding-a-new-administration-page.md]: yes, solved within fd487c8c43

File: docs/cookbook/adding-a-new-administration-page.md (hunk 6 above)
Comment (grossmannmartin) [reply docs/cookbook/adding-a-new-administration-page.md]: love it 💚

**Review by grossmannmartin — APPROVED** [review]

File: ecs.php [hunk 7]
```diff
@@ -132,6 +133,7 @@
             ForbiddenDumpSniff::class => [
                 __DIR__ . '/packages/framework/src/Component/DateTimeHelper/Exception/CannotParseDateTimeException.php',
                 __DIR__ . '/packages/framework/src/Twig/VarDumperExtension.php',
+                __DIR__ . '/packages/framework/src/Model/Security/AccessControl/RouteAccessControlDataProvider.php',
```
Comment (pk16011990) [inline ecs.php:136]: Is it necessary? I don't see any forbidden functions being used.

Comment (grossmannmartin) [reply ecs.php:136]: var_export probably

Comment (vitek-rostislav) [reply ecs.php:136]: yep, it is because of `var_export`
