### PR TITLE
[framework] fixed error 500 during logout when the user is already logged out

### LINKED ISSUE #769: 403 when trying to logout after my session expires
Reported by @stanoMilan 
### What is happening
I am logged customer on FE. When my session expires (can be reproduced manually by deleting the `PHPSESSID` cookie), I am logged out automatically in the background. Then, when I click on "Logout" (without refreshing the page before), I get an error - "403 - invalid CSRF token".

Notes: 
* probably connected to #315 
* @stanoMilan has some information about a fix that was already done on one of our internal projects.

### Expected result

I (as a logged customer) do not see any error when trying to logout. The fact, that I was logged out automatically before should not cause the application to crash.

### PR DESCRIPTION
**Pull request by TomasLudvik**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Application did end with 500 error page when user was trying to logout, when had not valid CSRF token. This has been fixed.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #769 closes #1559 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/Component/Error/LogoutExceptionSubscriber.php [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+     * @param \Symfony\Component\HttpKernel\Event\ExceptionEvent $event
+     */
+    public function onKernelException(ExceptionEvent $event): void
+    {
+        if ($event->getThrowable() instanceof LogoutException || $event->getThrowable()->getPrevious() instanceof LogoutException) {
+            if ($this->currentCustomerUser->findCurrentCustomerUser() !== null) {
+                $domainId = $this->currentCustomerUser->findCurrentCustomerUser()->getDomainId();
+                $locale = $this->domain->getDomainConfigById($domainId)->getLocale();
+
+                $this->flashBag->add(FlashMessage::KEY_ERROR, t('There was an error during logout attempt. If you really want to sign out, please try it again.', [], 'messages', $locale));
```
Comment (henzigo) [inline packages/framework/src/Component/Error/LogoutExceptionSubscriber.php:78]: I do not like this message in Framework bundle. As you know this translation will not be dumped in project-base, but it can be shown on Frontend. So you are not able to translate this message when you will do not know about that.

Comment (TomasLudvik) [reply packages/framework/src/Component/Error/LogoutExceptionSubscriber.php:78]: Ok, we have added upgrade note to warn developers about this

Comment (henzigo) [reply packages/framework/src/Component/Error/LogoutExceptionSubscriber.php:78]: But what about new projects? There will be same issue as I described

Comment (TomasLudvik) [reply packages/framework/src/Component/Error/LogoutExceptionSubscriber.php:78]: This is pros vs cons. 

Pro is that user do not end with 500 error during logging out, which might be really confusing and lead to bad feeling about such e-commerce solution. 

Con is that in really really weird state when:
- developers did not follow UPGRADE notes, because they do not need to when upgrading to patch / minor version
- user is logging out and somehow has wrong CSRF token
- on domain that is not in both English and Czech
happens:
- message is displayed in English saying, that there was some error and he should try it again

What do you think that is more possible to happen and what do you think is worse for both user and e-commerce solution owner?

Comment (TomasLudvik) [reply packages/framework/src/Component/Error/LogoutExceptionSubscriber.php:78]: Ok I was thinking what is the problem here and I now understand - framework translations displayed on frontend must be manually added to translations in project-base so they can be translated. 

Well I never thinked about this and found several such translations in framework. This is not easy thing to solve. I will create issue for that.

Comment (TomasLudvik) [reply packages/framework/src/Component/Error/LogoutExceptionSubscriber.php:78]: #1911

Comment (henzigo) [reply packages/framework/src/Component/Error/LogoutExceptionSubscriber.php:78]: I'm ok with issue that you created :) Thank you

Comment (TomasLudvik) [reply packages/framework/src/Component/Error/LogoutExceptionSubscriber.php:78]: Great, thank YOU for bringing this up!

**Comment by henzigo** [comment]
Hello, this PR didn't close issue and my PR. Can you look at it, please? :)

**Comment by TomasLudvik** [comment]
Hello @henzigo, it is because this PR was merged into 9.0 branch and not master. It should close after we merge 9.0 into master. This will happen in next days.

**Comment by henzigo** [comment]
Ok, thanks 👍
