### PR TITLE
[framework] fixed removing friendly urls

### LINKED ISSUE #668: [framework] Custom URL for Category
### What is happening
It is not possible to create own URL for a category

### What is happening
I am not able to create new URL for category and delete the one generated from category name.

Steps to reproduce:
1. Create a new URL for category and save.
2. Set the new URL as main and save.
3. Delete the original main URL that was generated from category name.

Once again, URL is generated from the category name and set as the main one.
Should be sufficient to remove one line from `CategoryFacade::edit()` where the new URL is generated.

### Expected result
Do not create an unwanted URL from category name.

### PR DESCRIPTION
**Pull request by s3tezsky**
| Q             | A
| ------------- | ---
|Description, reason for the PR| There was not any way how to remove default friendly URL for entities (product, category, brand or article). This PR makes it possible unless the entity is renamed.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #668  , also solves already closed PR #669
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/Component/Domain/Domain.php [hunk 1]
```diff
@@ -154,6 +154,18 @@ public function getDomainConfigById($domainId)
         throw new \Shopsys\FrameworkBundle\Component\Domain\Exception\InvalidDomainIdException();
     }
 
+    /**
+     * @return int[][]
```
Comment (TomasLudvik) [inline packages/framework/src/Component/Domain/Domain.php:158]:
```suggestion
     * @return int[]
```

We are trying to avoid this

File: packages/framework/src/Model/Category/CategoryFacade.php [hunk 2]
```diff
@@ -435,4 +438,27 @@ public function getListableProductCountsIndexedByCategoryId(
             $domainId
         );
     }
+
+    /**
+     * @param \Shopsys\FrameworkBundle\Model\Category\Category $category
+     * @param array $originalNames
+     */
+    protected function createFriendlyUrlWhenRenamed(Category $category, array $originalNames): void
```
Comment (TomasLudvik) [inline packages/framework/src/Model/Category/CategoryFacade.php:446]: This code is too complex, better would be to create only array of changed names and createUrls same as it was done in previous version on line 155.

File: packages/framework/src/Component/Domain/Domain.php (hunk 1 above)
Comment (s3tezsky) [reply packages/framework/src/Component/Domain/Domain.php:158]: Ok I will chaange that to `array` as your suggestion is not valid.

File: packages/framework/src/Model/Category/CategoryFacade.php (hunk 2 above)
Comment (s3tezsky) [reply packages/framework/src/Model/Category/CategoryFacade.php:446]: In previous version frienly urls were creaated for all domains every time.

Anyway, I reduced complexity in https://github.com/shopsys/shopsys/pull/1972/commits/cada8e61ed46f9ba8764d5d84d674a005564175b

File: packages/framework/src/Model/Category/CategoryFacade.php [hunk 3]
```diff
@@ -435,4 +438,33 @@ public function getListableProductCountsIndexedByCategoryId(
...
+    {
+        $this->friendlyUrlFacade->createFriendlyUrls(
```
Comment (TomasLudvik) [inline packages/framework/src/Model/Category/CategoryFacade.php:448]: You should call this only when some names are available

File: packages/framework/src/Model/Category/CategoryFacade.php [hunk 4]
```diff
@@ -435,4 +438,33 @@ public function getListableProductCountsIndexedByCategoryId(
             $domainId
         );
     }
+
+    /**
+     * @param \Shopsys\FrameworkBundle\Model\Category\Category $category
+     * @param array $originalNames
+     */
+    protected function createFriendlyUrlWhenRenamed(Category $category, array $originalNames): void
```
Comment (TomasLudvik) [inline packages/framework/src/Model/Category/CategoryFacade.php:446]:
```suggestion
    protected function createFriendlyUrlsWhenRenamed(Category $category, array $originalNames): void
```

Comment (s3tezsky) [reply packages/framework/src/Model/Category/CategoryFacade.php]: fixed

File: packages/framework/src/Model/Category/CategoryFacade.php (hunk 3 above)
Comment (s3tezsky) [reply packages/framework/src/Model/Category/CategoryFacade.php:453]: fixed
