### PR TITLE
[framework] fixed joining the same table with different alias

### LINKED ISSUE #1417: QueryBuilderExtender ignores different alias for joined table
### What is happening
When I call `QueryBuilderExtender::addOrExtendJoin()` with join which exists in query builder but with another alias, QueryBuilderExtender extends join instead of adding new join with different alias. Condition for new join contains new alias but It does not exist...

### Expected result
Passing test:
```php
public function testDifferentAlias()
{
    /** @var \Doctrine\ORM\EntityManager $entityManager */
    $entityManager = $this->getMockBuilder(EntityManagerInterface::class)
        ->disableOriginalConstructor()
        ->getMockForAbstractClass();

    $queryBuilder = new QueryBuilder($entityManager);
    $queryBuilder
        ->select('c')
        ->from(Category::class, 'c')
        ->join(Product::class, 'p', Join::WITH, 'p.id = 1');

    $queryBuilderExtender = new QueryBuilderExtender();
    $queryBuilderExtender->addOrExtendJoin($queryBuilder, Product::class, 'p2', 'p2.id = 2');

    $dql = $queryBuilder->getDQL();
    $this->assertSame('SELECT c FROM ' . Category::class . ' c INNER JOIN ' . Product::class . ' p WITH p.id = 1 INNER JOIN ' . Product::class . ' p2 WITH p2.id = 2', $dql);
}
```
not: 
```
1) Tests\FrameworkBundle\Unit\Component\Doctrine\QueryBuilderExtenderTest::testDifferentAlias
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'SELECT c FROM Shopsys\FrameworkBundle\Model\Category\Category c INNER JOIN Shopsys\ShopBundle\Model\Product\Product p WITH p.id = 1 INNER JOIN Shopsys\ShopBundle\Model\Product\Product p2 WITH p2.id = 2'
+'SELECT c FROM Shopsys\FrameworkBundle\Model\Category\Category c INNER JOIN Shopsys\ShopBundle\Model\Product\Product p WITH p.id = 1 WHERE p2.id = 2'

/var/www/html/packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php:36
```

### PR DESCRIPTION
**Pull request by s3tezsky**
| Q             | A
| ------------- | ---
|Description, reason for the PR| see #1417
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #1417 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php [hunk 1]
```diff
@@ -91,4 +92,35 @@ public function extendJoinWithExtendedEntityProvider(): array
...
+        );
+
+        $dql = $queryBuilder->getDQL();
+        $this->assertSame(
+            'SELECT c FROM ' . Category::class . ' c'
+            . ' INNER JOIN ' . Product::class . ' p WITH p.id = 1'
+            . ' INNER JOIN ' . Product::class . ' p2 WITH p2.id = 2',
+            $dql
+        );
+    }
```
Comment (grossmannmartin) [inline packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php:125]: 😍

Comment (s3tezsky) [reply packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php:125]: Yeah! Thanks to @pk16011990 for excelent issue 👏

File: packages/framework/src/Component/Doctrine/QueryBuilderExtender.php [hunk 2]
```diff
@@ -37,8 +37,7 @@ public function addOrExtendJoin(QueryBuilder $queryBuilder, $class, $alias, $con
         $joinAlreadyUsed = false;
         $resolvedClass = $this->entityNameResolver->resolve($class);
         foreach ($joins as $join) {
-            $resolvedJoinClass = $this->entityNameResolver->resolve($join->getJoin());
-            if ($resolvedJoinClass === $resolvedClass) {
+            if ($join->getAlias() === $alias) {
```
Comment (pk16011990) [inline packages/framework/src/Component/Doctrine/QueryBuilderExtender.php:40]: I think there should be compared alias and joined class together.

Comment (s3tezsky) [reply packages/framework/src/Component/Doctrine/QueryBuilderExtender.php:40]: Why do you think so? I think comparing alias only is enough as you cannot have same alias even for different classes.

Comment (grossmannmartin) [reply packages/framework/src/Component/Doctrine/QueryBuilderExtender.php:40]: Hi,
I have similar thoughts after testing.

Imagine the following code:

```php
$qb->select('oi.id')
    ->from(OrderItem::class, 'oi');

$queryBuilderExtender->addOrExtendJoin($qb, Product::class, 'p', 'oi.product = p.id');
$queryBuilderExtender->addOrExtendJoin($qb, Payment::class, 'p', 'oi.payment = p.id');
```
 resulting SQL is not what I expect (no join on payment)
```sql
SELECT o0_.id AS id_0 
FROM order_items o0_ 
INNER JOIN products p1_ ON (o0_.product_id = p1_.id) 
WHERE o0_.payment_id = p1_.id
```

now it's a pretty obvious mistake, but `addOrExtendJoin` can be in a different class, and then it could be really confusing because no error/warning is raised and code just doesn't do what you expect.

Comment (s3tezsky) [reply packages/framework/src/Component/Doctrine/QueryBuilderExtender.php:41]: Thanks for testing it this way! I have added one more test and fix this issue https://github.com/shopsys/shopsys/pull/1971/commits/3d1b7b943783c10afbf155ab43761d3d1f35eb88

File: packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+use Throwable;
+
+class DuplicatedAliasException extends LogicException
+{
+    /**
+     * @param string $alias
+     * @param int|null $code
+     * @param \Throwable|null $previous
+     */
+    public function __construct(string $alias, ?int $code = 0, ?Throwable $previous = null)
```
Comment (grossmannmartin) [inline packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php:17]: is the `$code` argument necessary? Usually, it's not used in extended exceptions (see other exceptions in the same namespace)

File: packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+    {
+        $message = sprintf(
+            'Alias "%s" is already assigned to different entity.',
+            $alias
+        );
+        parent::__construct(
+            $message,
```
Comment (grossmannmartin) [inline packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php:24]: Personally, I would prefer to have the sprintf on one line here, but as it's only a matter of personal preference I leave it up to you if you change it or not.

File: packages/framework/src/Component/Doctrine/QueryBuilderExtender.php (hunk 2 above)
Comment (grossmannmartin) [reply packages/framework/src/Component/Doctrine/QueryBuilderExtender.php:41]: nice!

File: packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+{
+    /**
+     * @param string $alias
+     * @param int|null $code
+     * @param \Throwable|null $previous
+     */
+    public function __construct(string $alias, ?int $code = 0, ?Throwable $previous = null)
+    {
+        $message = sprintf(
+            'Alias "%s" is already assigned to different entity.',
```
Comment (grossmannmartin) [inline packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php:20]: I'm thinking about a more verbose message, so it's really clear what's going on. 
What do you think of 

```php
sprintf('You cannot use "%s" as "%s" because this alias is already assigned to "%s" in the same QueryBuilder instance.',
    $resolvedClass,
    $alias,
    $resolvedJoinClass
);
```

`You cannot use "App\Model\Payment\Payment" as "p" because this alias is already assigned to "App\Model\Product\Product" in the same QueryBuilder instance.`

File: packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php (hunk 3 above)
Comment (s3tezsky) [reply packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php:17]: Yeah you are right.

File: packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php (hunk 4 above)
Comment (s3tezsky) [reply packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php:24]: Usually I would do it the way you are describing. I did not because the sprintf method is kind a large (and I personally do not like multiline function as an argument) and maybe will be even larger as you are suggesting change the message.

File: packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php (hunk 5 above)
Comment (s3tezsky) [reply packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php:20]: Nice point. I gues it will be the most descriptive exception in FW 😄

File: packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php (hunk 4 above)
Comment (grossmannmartin) [reply packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php:31]: 👌
