### PR TITLE
[project-base] fixed displaying errors in popup window

### LINKED ISSUE #1341: Duplicate flash message in error pop-up windows
### What is happening
A duplicate flash message appears if "ENTER" key is pressed in error pop-up window (steps are described in the screenshot below).

_bug-flashmessage

Screenshot URL: https://prnt.sc/ouzvwx

Tested on:
- Windows 10 Pro (version 1903) 64-bit
- Google Chrome 76.0.3809.100, Firefox 68.0.2, Microsoft Edge 44.18362.267.0

### Expected result
Only one validation error message is displayed.

### PR DESCRIPTION
**Pull request by s3tezsky**
| Q             | A
| ------------- | ---
|Description, reason for the PR| see #1341 
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #1341  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: project-base/assets/js/frontend/utils/showFormErrorsWindow.js [hunk 1]
```diff
@@ -14,11 +14,11 @@ export default function showFormErrorsWindow (container) {
...
         });
-    } else {
-        $window.filterAllNodes('.js-window-validation-errors')
-            .html($errorListHtml)
-            .removeClass('display-none');
     }
+
+    $window.filterAllNodes('.js-window-validation-errors')
+        .html($errorListHtml)
+        .removeClass('display-none');
```
Comment (grossmannmartin) [inline project-base/assets/js/frontend/utils/showFormErrorsWindow.js:23]: This I don't understand, can you please explain to me
1. why is it necessary to move it outside the else branch?
2. why do we need this at all?

File: project-base/assets/js/frontend/utils/Window.js [hunk 2]
```diff
@@ -55,8 +55,11 @@ export default class Window {
             $windowContent.append('<h2 class="' + this.options.cssClassHeading + '">' + this.options.textHeading + '</h2>');
         }
 
+        let displayClass = this.options.errors === undefined || this.options.errors === '' ? 'display-none' : '';
```
[the remark this answers is not in the document]
Comment (s3tezsky) [reply project-base/assets/js/frontend/utils/Window.js:58]: Nice point!

File: project-base/assets/js/frontend/utils/showFormErrorsWindow.js (hunk 1 above)
Comment (s3tezsky) [reply project-base/assets/js/frontend/utils/showFormErrorsWindow.js]: 1. Moved back into else block.
2. When we remove it the erros will dissapear on next enter key down.
