### PR TITLE
[project-base] fix dump function

### LINKED ISSUE #1535: Dump is not working properly
### What is happening

As Symfony programmer, I know that Symfony has global method `dump()` for debugging. Unfortunately, this method is not working well in SSFW. It's because of Tracy that is loaded before Symfony and registers his own method. 

This problem bothers the community because they do not know about our custom method `d();`

### Expected result

`dump()` is working properly and I can use it for debugging

### PR DESCRIPTION
**Pull request by henzigo**
| Q             | A
| ------------- | ---
|Description, reason for the PR| We are using shorter `d()` function for dumping some content, but most people out of Shopsys do not know about this function and they are trying to use Symfony built-in function `dump()` which is not working properly because of same function from Nette/Tracy package that is load instead of Symfony's function. A lot of people will be able to debug now :)
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #1535 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: project-base/app/autoload.php [hunk 1]
```diff
@@ -4,6 +4,10 @@
 
 use Doctrine\Common\Annotations\AnnotationRegistry;
 
+$symfonyDumpFunctionPath = 'vendor/symfony/var-dumper/Resources/functions/dump.php';
+
+file_exists(__DIR__ . '/../' . $symfonyDumpFunctionPath) ? require_once __DIR__ . '/../' . $symfonyDumpFunctionPath : require_once __DIR__ . '/../../' . $symfonyDumpFunctionPath;
```
Comment (grossmannmartin) [inline project-base/app/autoload.php:9]: this might kill whole application if `var-dumper` will not be installed. 
What about two separate file_exists conditions (monorepo/project)?

**Comment by grossmannmartin** [comment]
Ok, in monorepo it behaves as expected, but in project-base tracy is loaded first

<details><summary>vendor/composer/autoload_files.php</summary>

```php
return array(
    '9b38cf48e83f5d8f60375221cd213eee' => $vendorDir . '/phpstan/phpstan/bootstrap.php',
    '6124b4c8570aa390c21fafd04a26c69f' => $vendorDir . '/myclabs/deep-copy/src/DeepCopy/deep_copy.php',
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    '320cde22f66dd4f5d3fd621d3e88b98f' => $vendorDir . '/symfony/polyfill-ctype/bootstrap.php',
    '0d59ee240a4cd96ddbb4ff164fccea4d' => $vendorDir . '/symfony/polyfill-php73/bootstrap.php',
    '25072dd6e2470089de65ae7bf11d3109' => $vendorDir . '/symfony/polyfill-php72/bootstrap.php',
    'f598d06aa772fa33d905e87be6398fb1' => $vendorDir . '/symfony/polyfill-intl-idn/bootstrap.php',
    'c964ee0ededf28c96ebd9db5099ef910' => $vendorDir . '/guzzlehttp/promises/src/functions_include.php',
    '19a7e2c3b1d506dcdc1b60aab8e102e4' => $vendorDir . '/tracy/tracy/src/Tracy/shortcuts.php',
    '667aeda72477189d0494fecd327c3641' => $vendorDir . '/symfony/var-dumper/Resources/functions/dump.php',
    '6a47392539ca2329373e0d33e1dba053' => $vendorDir . '/symfony/polyfill-intl-icu/bootstrap.php',
    'def43f6c87e4f8dfd0c9e1b1bab14fe8' => $vendorDir . '/symfony/polyfill-iconv/bootstrap.php',
    '2c102faa651ef8ea5874edb585946bce' => $vendorDir . '/swiftmailer/swiftmailer/lib/swift_required.php',
    '7b11c4dc42b3b3023073cb14e519683c' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    'a0edc8309cc5e1d60e3047b5df6b7052' => $vendorDir . '/guzzlehttp/psr7/src/functions_include.php',
    '37a3dc5111fe8f707ab4c132ef1dbc62' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
    'ad155f8f1cf0d418fe49e248db8c661b' => $vendorDir . '/react/promise/src/functions_include.php',
    '8592c7b0947d8a0965a9e8c3d16f9c24' => $vendorDir . '/elasticsearch/elasticsearch/src/autoload.php',
    'e39a8b23c42d4e1452234d762b03835a' => $vendorDir . '/ramsey/uuid/src/functions.php',
    '3a9fdd577c9f0e05e3403f0a53c0909e' => $vendorDir . '/shopsys/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php',
    'c7ed1f246caaad8ee9fc31d7d336a8a0' => $vendorDir . '/shopsys/framework/src/Component/Translation/functions.php',
    '3b03cdf084351197c65f757dfabc1a28' => $vendorDir . '/shopsys/framework/src/Component/VarDumper/functions.php',
    '2a3c2110e8e0295330dc3d11a4cbc4cb' => $vendorDir . '/php-webdriver/webdriver/lib/Exception/TimeoutException.php',
);
```

</details>

I did not found any documentation about how composer sorts autoloaded files (random?). 
So I suggest to take into account my previous comment (https://github.com/shopsys/shopsys/pull/1745#discussion_r412536243) and accept this PR. (I tested it from PB)

File: project-base/app/autoload.php (hunk 1 above)
Comment (pesektomas) [reply project-base/app/autoload.php]: ab1f68532e84203045c75fd909c23c62e0ceb241
