### PR TITLE
FE API: rollback mutation & discard async messages on error

### LINKED ISSUE #2375: (GRAPQHL) FRONTEND API request is not in transaction (if throw exception)
## Describe the bug

Query from FRONTEND API (graphql) is not in transaction. 
Example:
Throw expcetion after create Order.
Create order by GRAPHQL . You have to see new order in adminstratrion. 

### Additional context
It is because, all graphql request finished with code 200. Overbolog bundle catch errors.

### PR DESCRIPTION
**Pull request by vitek-rostislav**
#### Description, the reason for the PR

GQL requests always return 200 OK (the errors are handled internally), so the error handlers listening on kernel errors are not called. This PR addresses that problem, so that DB transactions are rolled back when an error occurs during GQL mutation. Moreover, RabbitMQ messages are now discarded on an error within GQL request.

#### Fixes issues
closes #2515
closes #2375 

#### License Agreement for contributions

- [x] I have read and signed [License Agreement for contributions](https://www.shopsys.com/license-agreement)

----
:globe_with_meridians: Live Preview:
  - https://rv-mutation-rollback.odin.shopsys.cloud
  - https://cz.rv-mutation-rollback.odin.shopsys.cloud
  - https://rv-mutation-rollback.odin.shopsys.cloud/sk

----
:globe_with_meridians: Live Preview:
  - https://rv-mutation-rollback.odin.shopsys.cloud
  - https://cz.rv-mutation-rollback.odin.shopsys.cloud
  - https://rv-mutation-rollback.odin.shopsys.cloud/sk

### CODE REVIEW

**Comment by vitek-rostislav** [comment]
@coderabbitai review

File: packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+
+    public function onKernelResponse(ResponseEvent $event): void
+    {
+        if (!$this->shouldRollbackTransaction || !$event->isMainRequest() || !$this->em->getConnection()->isTransactionActive()) {
+            return;
+        }
+
+        TransactionalMasterRequestListener::setTransactionManuallyRollbacked();
+        $this->em->rollback();
+    }
```
[the remark this answers is not in the document]
Comment (vitek-rostislav) [reply packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php:70]: implemented in 470fb5099c

File: packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+
+    public function onKernelRequest(RequestEvent $event): void
+    {
+        if (!$event->isMainRequest()) {
+            return;
+        }
+
+        $this->shouldRollbackTransaction = false;
+    }
```
Comment (grossmannmartin) [inline packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php]: isn't this event superfluous? 
$shouldRollbackTransaction is already set to false from the object initialization. 

Maybe we could keep it as a safeguard (or if we adopt frankenphp). But I don't think the check for the main/sub request serves any practical purpose here

File: packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php (hunk 1 above)
Comment (grossmannmartin) [inline packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php:70]: I would reset the `shouldRollbackTransaction`

File: packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+    }
+
+    public function onPostExecutor(ExecutorResultEvent $event): void
+    {
+        if (count($event->getResult()->errors) === 0) {
+            return;
+        }
+
+        $this->delayedEnvelopesCollector->resetEnvelopes();
+    }
```
Comment (grossmannmartin) [inline packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php:41]: what about dispatching an event and handle this event in the `DispatchCollectedEnvelopesSubscriber`? that way we would have unified the place, where we handle/reset the collected envelopes

**Review by grossmannmartin — CHANGES_REQUESTED** [review]

File: packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php (hunk 3 above)
Comment (vitek-rostislav) [reply packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php:41]: That seems nice, however, `frontend-api` vs `framework` package problem comes to ruin our lives once again :smile: I mean, `DispatchCollectedEnvelopesSubscriber` is in `framework`, `GraphqlErrorResetDelayedEnvelopesSubscriber` is in `frontend-api`, and if I wanted to create a "graphQL error occurred" event to dispatch here, it should also be in `frontend-api` package, which is the `framework` package not aware of. 

We could create a general "collected messages should be reset" event in the `framework` package that could be then dispatched from the `frontend-api` package, but I am not sure whether that would be better than the current approach :shrug: IMHO, an event should represent what happened, not what should happen, right?

File: packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php (hunk 2 above)
Comment (vitek-rostislav) [reply packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php]: Makes sense, I have removed that in a171c98db5, along with resetting `shouldRollbackTransaction` in `onKernelResponse`

File: packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php (hunk 1 above)
Comment (vitek-rostislav) [reply packages/frontend-api/src/Component/HttpFoundation/GraphqlMutationErrorRollbackSubscriber.php:70]: added in a171c98db5aa91483f5e87356f8f5252e1e048da

File: packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php (hunk 3 above)
Comment (henzigo) [reply packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php:41]: Hm, are we talking about something like [this](https://github.com/shopsys/shopsys/pull/4017/changes/157976c9bb7ea69d8678822ab9f77e0bfc53137e)?

Comment (vitek-rostislav) [reply packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php:41]: Well, that is an antipattern in my opinion, it seems like reversed logic, listeners should be aware of events, not vice versa, I think :shrug: Lets discuss that tomorrow

Comment (vitek-rostislav) [reply packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php:41]: Btw, after asking Codex, whether `ManualRequestRollbackEvent` is a good practice, I got the following answer:
```
• Short answer: usually no.

  ManualRequestRollbackEvent is effectively a command disguised as an event (“listener,
  do rollback now”).
  That creates hidden coupling and makes flow harder to reason about.
```

Comment (vitek-rostislav) [reply packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php:41]: on the other hand, if we renamed `ManualRequestRollbackEvent` to something like `SilencedExceptionEvent`,  it could be a nice fit :+1: :slightly_smiling_face:

Comment (vitek-rostislav) [reply packages/frontend-api/src/Component/Messenger/GraphqlErrorResetDelayedEnvelopesSubscriber.php:41]: We could get rid of `TransactionalMasterRequestListener::setTransactionManuallyRollbacked();` completely if we had such an event. I like that idea

**Review by grossmannmartin — APPROVED** [review]
