### PR TITLE
[shopsys] fixed not working upload of files in wysiwyg editor

### LINKED ISSUE #1893: Wysiwyg file manager is broken
### What is happening
SSFW 9 has a corrupted file manager. First, the folder explorer does not work in it. Second, after uploading two images, both become one. Subsequently, only one can be inserted into the edited article. Furthermore, after right-clicking on any preview, a broken menu will open. After researching the problem, I came to the conclusion that there may be an incompatibility. In the Kernel there is a helios-ag / fm-elfinder-bundle package in version ^ 9.2 and it should be compatible with symfony 4. But version 10 already exists and it is for symfony 4.4. You will probably need to upgrade and resolve other custom adjustments, if any.

image

image

image

### PR DESCRIPTION
**Pull request by RostislavKreisinger**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Fix wysiwyg elfinger file manager and update to last version 10.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #1893  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/Command/ElFinderPostInstallCommand.php [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+use Symfony\Component\Console\Output\OutputInterface;
+use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
+use Symfony\Component\Filesystem\Filesystem;
+
+class ElFinderPostInstallCommand extends Command
+{
+    /**
+     * @var string
+     */
+    protected static $defaultName = 'shopsys:elfinder:postinstall';
```
Comment (TomasLudvik) [inline packages/framework/src/Command/ElFinderPostInstallCommand.php:18]:
```suggestion
    protected static $defaultName = 'shopsys:elfinder:post-install';
```

File: packages/framework/src/Command/ElFinderPostInstallCommand.php [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+     */
+    private $parameterBag;
+
+    /**
+     * @param \Symfony\Component\Filesystem\Filesystem $filesystem
+     * @param \Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface $parameterBag
+     */
+    public function __construct(Filesystem $filesystem, ParameterBagInterface $parameterBag)
+    {
+        parent::__construct();
```
Comment (TomasLudvik) [inline packages/framework/src/Command/ElFinderPostInstallCommand.php:36]:
```suggestion
        parent::__construct();

```

File: packages/framework/src/Command/ElFinderPostInstallCommand.php [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+    /**
+     * @param \Symfony\Component\Console\Input\InputInterface $input
+     * @param \Symfony\Component\Console\Output\OutputInterface $output
+     */
+    protected function execute(InputInterface $input, OutputInterface $output)
+    {
+        $publicDir = $this->parameterBag->get('kernel.project_dir') . '/public/bundles/fmelfinder';
+        $webDir = $this->parameterBag->get('kernel.project_dir') . '/web/bundles/fmelfinder';
+
+        if (!$this->filesystem->exists($webDir . '/css') && $this->filesystem->exists($publicDir . '/css')) {
```
Comment (TomasLudvik) [inline packages/framework/src/Command/ElFinderPostInstallCommand.php:50]: Why are you looking for css folder?

File: packages/framework/src/Command/ElFinderPostInstallCommand.php [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+            $output->writeln('<fg=green>move elFinder from ' . $publicDir . ' to ' . $webDir . ' </fg=green>');
+
+            $this->filesystem->mirror($publicDir, $webDir);
+
+            $output->writeln('<fg=green>remove elFinder public directory </fg=green>');
+            $this->filesystem->remove($publicDir);
+        }
+
+        if ($this->filesystem->exists($webDir . '/css')) {
```
Comment (TomasLudvik) [inline packages/framework/src/Command/ElFinderPostInstallCommand.php:59]: Again css folder

File: packages/framework/src/Command/ElFinderPostInstallCommand.php [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+            $output->writeln('<fg=green>elFinder assets successfully post-installed</fg=green>');
+            return CommandResultCodes::RESULT_OK;
+        } else {
+            $output->writeln('<fg=red>elFinder POST install FAILED</fg=red>');
```
Comment (TomasLudvik) [inline packages/framework/src/Command/ElFinderPostInstallCommand.php:63]:
```suggestion
            $output->error('elFinder post install failed');
```

File: packages/framework/src/Command/ElFinderPostInstallCommand.php [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+            $output->writeln('<fg=green>move elFinder from ' . $publicDir . ' to ' . $webDir . ' </fg=green>');
+
+            $this->filesystem->mirror($publicDir, $webDir);
+
+            $output->writeln('<fg=green>remove elFinder public directory </fg=green>');
+            $this->filesystem->remove($publicDir);
+        }
+
+        if ($this->filesystem->exists($webDir . '/css')) {
+            $output->writeln('<fg=green>elFinder assets successfully post-installed</fg=green>');
```
Comment (TomasLudvik) [inline packages/framework/src/Command/ElFinderPostInstallCommand.php:60]:
```suggestion
            $output->success('elFinder assets successfully installed');
```

File: packages/framework/src/Command/ElFinderPostInstallCommand.php [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+     * @param \Symfony\Component\Console\Input\InputInterface $input
+     * @param \Symfony\Component\Console\Output\OutputInterface $output
+     */
+    protected function execute(InputInterface $input, OutputInterface $output)
+    {
+        $publicDir = $this->parameterBag->get('kernel.project_dir') . '/public/bundles/fmelfinder';
+        $webDir = $this->parameterBag->get('kernel.project_dir') . '/web/bundles/fmelfinder';
+
+        if (!$this->filesystem->exists($webDir . '/css') && $this->filesystem->exists($publicDir . '/css')) {
+            $output->writeln('<fg=green>move elFinder from ' . $publicDir . ' to ' . $webDir . ' </fg=green>');
```
Comment (TomasLudvik) [inline packages/framework/src/Command/ElFinderPostInstallCommand.php:51]:
```suggestion
            $output->writeln('Moving elFinder from ' . $publicDir . ' to ' . $webDir);
```

File: packages/framework/src/Command/ElFinderPostInstallCommand.php [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+
+            $this->filesystem->mirror($publicDir, $webDir);
+
+            $output->writeln('<fg=green>remove elFinder public directory </fg=green>');
```
Comment (TomasLudvik) [inline packages/framework/src/Command/ElFinderPostInstallCommand.php:55]:
```suggestion
            $output->writeln('Removing elFinder public directory');
```

File: packages/framework/build.xml [hunk 9]
```diff
@@ -106,6 +106,14 @@
...
             <arg value="${path.root}/web/"/>
         </exec>
+        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
+            <arg value="${path.bin-console}"/>
+            <arg value="elfinder:install"/>
+        </exec>
+        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
+            <arg value="${path.bin-console}"/>
+            <arg value="shopsys:elfinder:postinstall"/>
+        </exec>
```
Comment (TomasLudvik) [inline packages/framework/build.xml:116]: I would move this to `composer.json` -> `scripts` -> `auto-scripts`

File: packages/framework/src/Command/ElFinderPostInstallCommand.php [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+        $this->filesystem = $filesystem;
+        $this->parameterBag = $parameterBag;
+    }
+
+    /**
+     * @param \Symfony\Component\Console\Input\InputInterface $input
+     * @param \Symfony\Component\Console\Output\OutputInterface $output
+     */
+    protected function execute(InputInterface $input, OutputInterface $output)
+    {
```
Comment (TomasLudvik) [inline packages/framework/src/Command/ElFinderPostInstallCommand.php:46]:
```suggestion
    {
        $symfonyStyleIo = new SymfonyStyle($input, $output);
```

File: packages/framework/src/Command/ElFinderPostInstallCommand.php (hunk 3 above)
Comment (RostislavKreisinger) [reply packages/framework/src/Command/ElFinderPostInstallCommand.php:50]: Because its one of four folders installed by elfinger installator and it's sufficient condition.

File: packages/framework/src/Command/ElFinderPostInstallCommand.php (hunk 4 above)
Comment (RostislavKreisinger) [reply packages/framework/src/Command/ElFinderPostInstallCommand.php:59]: Because its one of four folders installed by elfinger installator and it's sufficient condition.

File: packages/framework/src/Command/ElFinderPostInstallCommand.php (hunk 5 above)
Comment (RostislavKreisinger) [reply packages/framework/src/Command/ElFinderPostInstallCommand.php:63]: ok

File: packages/framework/src/Command/ElFinderPostInstallCommand.php (hunk 6 above)
Comment (RostislavKreisinger) [reply packages/framework/src/Command/ElFinderPostInstallCommand.php:60]: ok

File: packages/framework/src/Command/ElFinderPostInstallCommand.php (hunk 7 above)
Comment (RostislavKreisinger) [reply packages/framework/src/Command/ElFinderPostInstallCommand.php:51]: ok

File: packages/framework/src/Command/ElFinderPostInstallCommand.php (hunk 8 above)
Comment (RostislavKreisinger) [reply packages/framework/src/Command/ElFinderPostInstallCommand.php:55]: ok

File: packages/framework/src/Command/ElFinderPostInstallCommand.php (hunk 10 above)
Comment (RostislavKreisinger) [reply packages/framework/src/Command/ElFinderPostInstallCommand.php:46]: I found it myself :-)

File: packages/framework/src/Command/ElFinderPostInstallCommand.php (hunk 1 above)
Comment (RostislavKreisinger) [reply packages/framework/src/Command/ElFinderPostInstallCommand.php:18]: ok

File: project-base/config/bootstrap.php [hunk 11]
```diff
@@ -56,3 +56,6 @@
 $_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? null) ?: 'dev';
 $_SERVER['APP_DEBUG'] = $_SERVER['APP_DEBUG'] ?? $_ENV['APP_DEBUG'] ?? 'prod' !== $_SERVER['APP_ENV'];
 $_SERVER['APP_DEBUG'] = $_ENV['APP_DEBUG'] = (int) $_SERVER['APP_DEBUG'] || filter_var($_SERVER['APP_DEBUG'], FILTER_VALIDATE_BOOLEAN) ? '1' : '0';
+
+
+define('ELFINDER_IMAGEMAGICK_PS', false);
```
[the remark this answers is not in the document]
Comment (RostislavKreisinger) [reply project-base/config/bootstrap.php:61]: this constant is expected in the elfinder package, but nowhere in the code is it defined, or rather the definition is there, but it does not set this constant. If there is a better place to define this, then I do not know about it.

File: packages/framework/src/Command/ElFinderPostInstallCommand.php (hunk 2 above)
Comment (RostislavKreisinger) [reply packages/framework/src/Command/ElFinderPostInstallCommand.php:37]: ok

File: packages/framework/build.xml (hunk 9 above)
Comment (RostislavKreisinger) [reply packages/framework/build.xml]: the commands to install elfinder have to be after assets:install because it deletes folder where the elfider is installed

File: project-base/config/routes/fm_elfinder.yaml [hunk 12]
```diff
@@ -1,2 +1,2 @@
 fm_elfinder:
-    resource: "@FMElfinderBundle/Resources/config/routing.yml"
+    resource: "@FMElfinderBundle/Resources/config/routing.yaml"
```
Comment (grossmannmartin) [inline project-base/config/routes/fm_elfinder.yaml:2]: file was renamed to yaml in version `10.0.1`, minimum required version is 10.0 according to composer.json and that version will not work.
I suggest to increase version in composer.json

File: packages/framework/build.xml [hunk 13]
```diff
@@ -106,6 +106,14 @@
...
             <arg value="${path.root}/web/"/>
         </exec>
+        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
+            <arg value="${path.bin-console}"/>
+            <arg value="elfinder:install"/>
+        </exec>
+        <exec executable="${path.php.executable}" passthru="true" checkreturn="true">
+            <arg value="${path.bin-console}"/>
+            <arg value="shopsys:elfinder:post-install"/>
+        </exec>
```
Comment (grossmannmartin) [inline packages/framework/build.xml:116]: Is it worth to mention this change in upgrade notes?

File: symfony.lock [hunk 14]
```diff
@@ -846,6 +849,9 @@
     "symfony/polyfill-php73": {
         "version": "v1.12.0"
     },
+    "symfony/polyfill-php80": {
+        "version": "v1.17.0"
+    },
```
Comment (grossmannmartin) [inline symfony.lock:854]: Just wondering, don't you know why polyfill for php8 is installed?

Comment (TomasLudvik) [reply symfony.lock:854]: I do not

File: project-base/config/routes/fm_elfinder.yaml (hunk 12 above)
Comment (TomasLudvik) [reply project-base/config/routes/fm_elfinder.yaml:2]: Done

File: packages/framework/build.xml (hunk 13 above)
Comment (TomasLudvik) [reply packages/framework/build.xml:116]: Yes, there are changed files in project-base

Comment (grossmannmartin) [reply packages/framework/build.xml:116]: This file is not from a project-base :)
