### PR TITLE
[shopsys] prevent admin to log as customer user on a different domain than user is registered on

### LINKED ISSUE #2198: Administrator can log in himself as a customer on different domain
## Describe the bug

As an administratort I can login as a user on different domain than user is registred to.

### To Reproduce

1. Go to Administration -> Customers -> switch to second domain -> click on any customer
2. Copy link from `login as customer` (`http://127.0.0.1:8000/admin/sso/2?originalReferer=http://127.0.0.2:8000/admin/customer/login-as-user/8/`), change url to `http://127.0.0.1:8000/admin/sso/2?originalReferer=http://127.0.0.1:8000/admin/customer/login-as-user/8/` and paste it into your browser.
3. Now you are logged in as second domain user on first domain

### Expected behavior

You can login as customer on his domain only.

### PR DESCRIPTION
**Pull request by TomasLudvik**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Admin should not be able to log as user on different domains that is supposed to be.
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #2198 
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/Model/Administrator/Security/AdministratorFrontSecurityFacade.php [hunk 1]
```diff
@@ -40,22 +42,56 @@ class AdministratorFrontSecurityFacade
      */
     protected $authorizationChecker;
 
+    /**
+     * @var \Shopsys\FrameworkBundle\Component\Domain\Domain|null
+     */
+    protected ?Domain $domain;
```
Comment (vitek-rostislav) [inline packages/framework/src/Model/Administrator/Security/AdministratorFrontSecurityFacade.php:48]: `protected ?Domain $domain = null`? To avoid initialized property in extended class? :thinking:

File: packages/framework/src/Model/Security/LoginAsUserFacade.php [hunk 2]
```diff
@@ -43,25 +45,59 @@ class LoginAsUserFacade
      */
     protected $administratorFrontSecurityFacade;
 
+    /**
+     * @var \Shopsys\FrameworkBundle\Component\Domain\Domain|null
+     */
+    protected ?Domain $domain;
```
Comment (vitek-rostislav) [inline packages/framework/src/Model/Security/LoginAsUserFacade.php:51]: same as above, initialize it to null?

File: packages/framework/src/Twig/LoggedAsCustomerUserExtension.php [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+use Shopsys\FrameworkBundle\Model\Administrator\Security\AdministratorFrontSecurityFacade;
+use Twig\Extension\AbstractExtension;
+use Twig\TwigFunction;
+
+class LoggedAsCustomerUserExtension extends AbstractExtension
+{
+    /**
+     * @var \Shopsys\FrameworkBundle\Model\Administrator\Security\AdministratorFrontSecurityFacade
+     */
+    public AdministratorFrontSecurityFacade $administratorFrontSecurityFacade;
```
Comment (vitek-rostislav) [inline packages/framework/src/Twig/LoggedAsCustomerUserExtension.php:16]: protected?

**Review by vitek-rostislav — CHANGES_REQUESTED** [review]
Hi, I have added just a few notes. Plus one question - what happens when you as admin log in as a customer on 2nd domain, and then access the first domain :thinking:

File: packages/framework/src/Controller/Admin/CustomerController.php [hunk 4]
```diff
@@ -296,6 +334,11 @@ public function deleteAction($id)
     public function loginAsUserAction($customerUserId)
     {
         $customerUser = $this->customerUserFacade->getCustomerUserById($customerUserId);
+
+        if ($this->domain->getId() !== $customerUser->getDomainId()) {
```
Comment (vitek-rostislav) [inline packages/framework/src/Controller/Admin/CustomerController.php:338]: I am thinking - this way you will never be able to log as a customer on the 2nd domain when accessing administration on the 1st domain, and vice versa. And moreover, the admin will not know what is happening (no flash message here). Or am I missing something

**Review by sslt — APPROVED** [review]

**Review by vitek-rostislav — APPROVED** [review]
