### PR TITLE
[framework] fixed throwing OrderItemNotFoundException

### LINKED ISSUE #1898: Wrong argument sent to OrderItemNotFoundException
### What is happening

Class `Shopsys\FrameworkBundle\Model\Order\Order` attempts to throw `OrderItemNotFoundException` on line 725 but it supplies `array` instead of `string|null` as the first argument so `TypeError` is thrown instead. 

### Expected result

Either `OrderItemNotFoundException` should override its parent construct to accept `array` as the first argument or `string` should be supplied as the first argument.

### PR DESCRIPTION
**Pull request by s3tezsky**
| Q             | A
| ------------- | ---
|Description, reason for the PR| ...
|New feature| No 
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| closes #1898  
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: packages/framework/src/Model/Order/Order.php [hunk 1]
```diff
@@ -722,7 +722,10 @@ public function getItemById($orderItemId)
                 return $orderItem;
             }
         }
-        throw new \Shopsys\FrameworkBundle\Model\Order\Item\Exception\OrderItemNotFoundException(['id' => $orderItemId]);
+        throw new \Shopsys\FrameworkBundle\Model\Order\Item\Exception\OrderItemNotFoundException(sprintf(
+            'Order item `%s` not found.',
```
Comment (TomasLudvik) [inline packages/framework/src/Model/Order/Order.php:726]:
```suggestion
            'Order item id `%d` not found.',
```
